add vacancy filter on vacancies lists
Hexlet/hexlet-cv pull request #307
Opened 2021-12-24 14:26 UTC by LubaRo

2021-12-24 14:28 UTC, LubaRo commented
#290 

Реализовала фильтрацию вакансий через существующий механизм, перенаправляя пользователя на нужную страницу, исходя из параметров поиска

----

![vacancy filter](https://user-images.githubusercontent.com/29543596/147359085-c53cf113-960d-4f54-b57e-9a2f80ff2b32.png)

2021-12-26 17:18 UTC, ralder requested changes
Привет. спасибо за ПР ;)
В целом все хорошо но хорошо бы внести несколько правок)

2021-12-26 17:18 UTC, ralder commented on app/controllers/web/vacancy_filters_controller.rb
> +      result[:city] = decode_value(city).capitalize
эсли это делается только для вывода в представлении, то нужно делать либо в ридере поля класса формы, либо во вьюхе

2021-12-26 17:18 UTC, ralder commented on app/forms/web/vacancies/search_form.rb
> +  include ActiveModel::Model
на этой неделе обновим гем на 4 версию https://github.com/Hexlet/active_form_model
и нужно будет переписать как у там в примере для SignInForm

2021-12-26 17:18 UTC, ralder commented on app/views/web/shared/_vacancy_filter.html.slim
> +  = simple_form_for @vacancy_search_form, default_filter_form_options(url: search_vacancy_filters_path, wrapper: :horizontal_search_form_with_hints) do |f|
раз шаблон в shared значит не используем переменные класса контроллера и нужно делать входные параметры с явной передачей

2021-12-26 17:18 UTC, ralder requested changes
Привет. спасибо за ПР ;)
В целом все хорошо но хорошо бы внести несколько правок)

2021-12-29 06:29 UTC, ralder commented on app/forms/web/vacancies/search_form.rb
> +  include ActiveModel::Model
опубликовали новую версию https://rubygems.org/gems/active_form_model 0.4.1

2022-01-10 13:30 UTC, ralder approved these changes

2022-01-10 13:30 UTC, merged

2022-01-11 08:53 UTC, ralder commented
@LubaRo чета мы где-то проглядели баг https://github.com/Hexlet/hexlet-cv/issues/308

2022-01-11 08:58 UTC, LubaRo commented
@ralder  Да, похоже проблема в регистре вариантов, когда из урла парсим, то они все donwcase, а  форме value  не приведены к нижнему регистру, а отдаются как есть.