Add the property locale to all entities and if the user is ru, he will have everything in russian
Hexlet/hexlet-cv pull request #390
Opened 2022-10-26 18:14 UTC by askorutin26

Добавлено переключение языков, en - локаль по умолчанию
Наверно относится и к этому issue https://github.com/Hexlet/hexlet-cv/issues/379

2022-10-28 08:54 UTC, amshkv reviewed
пока не понимаю как эта система работает, надо проверить в живую
ссылки точно стоит поправить уже сейчас, как на code-basics

2022-10-28 08:54 UTC, amshkv commented on config/locales/en.layouts.yml
> +    application:
зачем пустой ключ?
ПыСы: у тебя редактор не настроен на добавление пустых строк в конце файла?

2022-10-28 08:54 UTC, amshkv commented on app/views/layouts/shared/_footer.html.slim
> +          li = link_to t('.guides'), 'https://guides.hexlet.io/', target: '_blank', rel: :noopener, class: 'link-dark'
переводы как бы есть, а ссылки как бы не правильные, например code-basics всегда будет ru
а гайды наоборот (скорее всего)

2022-10-28 08:54 UTC, amshkv commented on app/views/layouts/shared/_nav.html.slim
> +    a.d-flex.align-items-center.mb-2.mb-md-0.me-5.text-dark.text-decoration-none.fs-4(href="/") = t('.name')
а чем application_name не устроил?

2022-10-28 13:23 UTC, askorutin26 commented on config/locales/en.layouts.yml
> +    application:
пустой ключ не заметил, редактор не настроен скорее всего, нужно чтобы добавлял?

2022-10-28 13:26 UTC, askorutin26 commented on app/views/layouts/shared/_nav.html.slim
> +    a.d-flex.align-items-center.mb-2.mb-md-0.me-5.text-dark.text-decoration-none.fs-4(href="/") = t('.name')
на русской версии было Hexlet cv, на английской не переводило, было application name, я решил закинуть в файл с переводами, чтобы оттуда брало

2022-10-28 13:34 UTC, askorutin26 commented on config/locales/en.layouts.yml
> +    application:
в ru.layouts.yml также пустой ключ в конце, просто структуру оттуда копировал: https://github.com/Hexlet/hexlet-cv/blob/main/config/locales/ru.layouts.yml

2022-10-28 14:32 UTC, askorutin26 commented on app/views/layouts/shared/_footer.html.slim
> +          li = link_to t('.guides'), 'https://guides.hexlet.io/', target: '_blank', rel: :noopener, class: 'link-dark'
а как лучше сделать? указать в файлах перевода разные ссылки в зависимости от локали?

2022-11-05 01:22 UTC, usernaimandrey reviewed
Привет) Смотри у тебя сейчас это все работает не так как должно по ТЗ: должно быть так если у пользователя английская локаль то в url это не должно отображаться(https://cv.hexlet.io/), а вот если русская то должно(https://cv.hexlet.io/ru)
Кстати можно вот здесь посмотреть https://github.com/hexlet-basics/hexlet-basics/pull/321/files

2022-11-05 13:15 UTC, askorutin26 commented
> Привет) Смотри у тебя сейчас это все работает не так как должно по ТЗ: должно быть так если у пользователя английская локаль то в url это не должно отображаться(https://cv.hexlet.io/), а вот если русская то должно(https://cv.hexlet.io/ru) Кстати можно вот здесь посмотреть https://github.com/hexlet-basics/hexlet-basics/pull/321/files

Приветствую! Этот момент я исправил, добавлял несколько новых коммитов после

2022-11-05 19:35 UTC, usernaimandrey commented
Подскажи а в каком комите я не увидел

2022-11-05 19:41 UTC, usernaimandrey commented on app/controllers/concerns/locale_concern.rb
> +  def extract_locale_from_subdomain
Еще сразу от себя добавлю, у метода extract_locale_from_subdomain не совсем удачное название, ты же локаль не из поддомена получаешь в нем, а из параметров, можно назвать locale_params например

2022-11-05 19:42 UTC, askorutin26 commented
> Подскажи а в каком комите я не увидел

ну там несколько, в общем этот с default url: 
 https://github.com/Hexlet/hexlet-cv/pull/390/commits/7c7d9359291b9ae10258bbcecad21042d6248249
 тут попытался создать ссылку для переключения языка, чтобы url стоился правильно:
 https://github.com/Hexlet/hexlet-cv/pull/390/commits/b4e033345e99872f964a66516eebe29c4023e62e
 а так второй блок коммитов: 
 
![image](https://user-images.githubusercontent.com/66885436/200138071-42f69668-df33-42b4-aaa3-86b670af16c6.png)

2022-11-05 19:44 UTC, askorutin26 commented on app/controllers/concerns/locale_concern.rb
> +  def extract_locale_from_subdomain
да, нужно поменять

2022-11-05 19:48 UTC, askorutin26 commented on app/controllers/concerns/locale_concern.rb
> +  def extract_locale_from_subdomain
еще осталась проблема, когда стоит русская локаль и нажимаешь на лого hexlet cv, переходит на главную и язык устанавливается английский, по умолчанию,  на hexlet basics видел что локаль как то сохраняется в session, пока не разобрался

2022-11-05 20:03 UTC, usernaimandrey commented on app/controllers/concerns/locale_concern.rb
> +  def extract_locale_from_subdomain
Да знаю, я тестил твой код, просто мы с тобой над одной задачей работаем, только разными частями, я в другом коммите добавил аттрибут locale в resume и vacancy и соответствено как только разберемся с переключением локали, сущности в базе данных будут создаваться в соответствии с локалью и выборки из бд тоже будут делаться в соответствии с локалью. Вобщем я тоже подумаю над этим, если у тебя будут вопросы пиши мне в слак @Андрей Шляпников

2022-11-05 20:31 UTC, askorutin26 commented on app/controllers/concerns/locale_concern.rb
> +  def extract_locale_from_subdomain
понял, хорошо

2022-11-17 05:20 UTC, acidmaksim commented
@grozwalker сделай, пожалуйста ревью

2022-11-17 08:17 UTC, grozwalker commented on app/views/layouts/shared/_footer.html.slim
> +          li = link_to t('.guides'), 'https://guides.hexlet.io/', target: '_blank', rel: :noopener, class: 'link-dark'
да, в переводе будет хорошо сделать

2022-11-20 23:31 UTC, usernaimandrey commented on app/controllers/concerns/locale_concern.rb
> +  def extract_locale_from_subdomain
> еще осталась проблема, когда стоит русская локаль и нажимаешь на лого hexlet cv, переходит на главную и язык устанавливается английский, по умолчанию, на hexlet basics видел что локаль как то сохраняется в session, пока не разобрался

Привет! У тебя тут workflow упал и надо конфликт разрезодвить. Скажи получилось ли решить проблему с преключением

2022-11-21 20:17 UTC, askorutin26 commented on app/controllers/concerns/locale_concern.rb
> +  def extract_locale_from_subdomain
@usernaimandrey Привет, тесты вроде поправил, сделал чтобы локаль сохранялась в сессии, теперь по клику по лого язык сохраняется.
 Но теперь проблема c url, не совсем понимаю как все это работает:
Клик по лого всегда редиректит на http://localhost:3000/, но сайт переведен на выбранный язык
Ссылку для переключения языка поменял на url_for(locale), она меняет locale для текущей страницы и отображает ее, это нужно поменять, пока не знаю как получать url + опциональную локаль
 Страницы работают как надо, в url есть locale для русского, и нет для английского

2022-11-21 21:04 UTC, usernaimandrey commented
Теперь бы еще конфликт испарвить)

2022-11-29 09:10 UTC, acidmaksim commented
@askorutin26 Здесь нужно поправить конфликты и историю коммитов

2022-11-30 10:27 UTC, acidmaksim commented
@askorutin26 напиши мне в слаке

2022-12-27 10:26 UTC, fey commented
@askorutin26 привет. Как успехи. нужна помощь?

2022-12-27 13:37 UTC, askorutin26 commented
> @askorutin26 привет. Как успехи. нужна помощь?

привет! перевод и переключение языка работает, не знаю нужно ли что-то менять и правильно ли сделано

2022-12-27 13:50 UTC, fey commented
У тебя сейчас в ПРе конфликты. Получится самостоятельно поправить? 
Ты можешь в слаке студентов в канале internship пингануть и созвонимся и поможем. Или в слаке сообщества, если ты не студент в канале hexlet-volunteers

2022-12-27 14:05 UTC, askorutin26 commented
> У тебя сейчас в ПРе конфликты. Получится самостоятельно поправить? Ты можешь в слаке студентов в канале internship пингануть и созвонимся и поможем. Или в слаке сообщества, если ты не студент в канале hexlet-volunteers

да, поправлю

2023-01-09 10:19 UTC, dzencot commented
Тут все готово? Мержим?

2023-01-09 15:07 UTC, fey commented
Такое без ревью разработчиков нельзя мержить.

2023-01-09 15:25 UTC, askorutin26 commented
> @askorutin26 как успехи? Можно уже ревьювить?

Думаю да, можно

2023-01-10 13:45 UTC, grozwalker requested changes
Уже очень много сделано и из такого большого осталось  только создать контроллер для переключения языков, но по идее и это не очень много!

Спасибо за такую большую проделанную работу, ждем фикс коммита и будем мерджить! если будут какие-то вопросы -- пиши, постараюсь помочь

2023-01-10 13:45 UTC, grozwalker commented on app/controllers/application_controller.rb
> +  def default_url_options(_options = {})
Давай уберем `_options = {}`, тк оно здесь никак не используется

2023-01-10 13:45 UTC, grozwalker commented on app/controllers/concerns/locale_concern.rb
> +  def switch_locale(&)
Сейчас подумал вот о чем:
1. А что будет, если в params[:locale] передать локаль, которой у нас нету, например,`de`? По идее мы же должны проверять, что у нас корректная локаль передается
2. Метод extract_locale похоже нигде не используется, а его как раз можно заюзать, чтобы посмотреть, корректная ли локаль в парамсах пришла

И я бы даже немного переписал этот код как-нибудь так:
```
locale = params[:locale].present? ? extract_locale_from_params : I18n.default_locale

I18n.with_locale(locale, &)
```

Просто мне без ифа кажется более красивишно и понятно, но думаю это вкусовщина)

2023-01-10 13:45 UTC, grozwalker commented on app/controllers/web/application_controller.rb
> +  around_action :switch_locale
По идее здесь это уже не надо, тк ты в концерне прописал включение этого метода

2023-01-10 13:45 UTC, grozwalker commented on app/helpers/application_helper.rb
> +  def root_url
Вот это надо удолить

2023-01-10 13:45 UTC, grozwalker commented on app/views/layouts/shared/_nav.html.slim
> +    a.d-flex.align-items-center.mb-2.mb-md-0.me-5.text-dark.text-decoration-none.fs-4(href=root_url) = t('.name')
а здесь заменить root_url на root_path и проблемы не должно быть

2023-01-10 13:45 UTC, grozwalker commented on app/helpers/application_helper.rb
> +  def switch_locale_url(locale)
Не  очень понял зачем это код( Похоже, что вместо того, чтобы сделать роут с экшеном по изменению локали, ты добавил вот такой хэлпер, тогда получается у тебя какая-то логика в хэлпере, который для этого не предназначен. Давай это переделаем. Этот метод в целом можно весь удалить (если я правильно понял его назначение)

2023-01-10 13:45 UTC, grozwalker commented on app/helpers/application_helper.rb
> +  def switch_locale_url(locale)
Ниже напишу как лучше сделать переключение

2023-01-10 13:45 UTC, grozwalker commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
По переключению языков: 
этот скоуп надо вынести глобально наверх, потому что все роуты должны быть с локализацией
```
  scope '(:locale)', locale: /en|ru/ do
    scope module: :web do
      root 'home#index'
```
Подсмотреть можно здесь https://github.com/hexlet-basics/hexlet-basics/blob/main/config/routes.rb#L22

Далее где-то внутри должен быть роут на  ресурсный контроллер, который будет переключать язык и редиректить на корректный урл
```
      resource :locale, only: [] do
        member do
          get :switch
        end
      end
```
https://github.com/hexlet-basics/hexlet-basics/blob/main/config/routes.rb#L45

И потом надо создать сам LocalesController с методом switch
Будет выглядить примерно вот так: https://github.com/hexlet-basics/hexlet-basics/blob/main/app/controllers/web/locales_controller.rb только без сохранения локали в пользователя и сессию

И еще в выпадающем меню переключения языка надо параметр передавать new_locale  и вроде все

2023-01-11 01:46 UTC, askorutin26 commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
Благодарю за ревью!
По поводу кнопки переключения, вот это метод в application helper
```
def switch_locale_url(locale)
    if locale == I18n.default_locale
      url_for('locale' => nil)
    else
      url_for('locale' => locale)
    end
  end
```
через него получал текущий url с /ru или без, не очень понял как теперь url для перключения создавать, вот с new_locale в code basics, не нашел метод  switch_locale_path
`link_to switch_locale_path(new_locale: locale)`

2023-01-11 01:50 UTC, askorutin26 commented on app/helpers/application_helper.rb
> +  def seo_for_paging(number_page, text)
пытался править конфликт, не очень понимал механизм, подумал из-за того что в моей версии файла нет этого кода

2023-01-11 19:10 UTC, usernaimandrey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
> Благодарю за ревью! По поводу кнопки переключения, вот это метод в application helper
> 
> ```
> def switch_locale_url(locale)
>     if locale == I18n.default_locale
>       url_for('locale' => nil)
>     else
>       url_for('locale' => locale)
>     end
>   end
> ```
> 
> через него получал текущий url с /ru или без, не очень понял как теперь url для перключения создавать, вот с new_locale в code basics, не нашел метод switch_locale_path `link_to switch_locale_path(new_locale: locale)`

Привет! Если я правельно понял твой вопрос) switch_locale_path - это хелпер который автоматически сгенерирует рельса, когда ты пропишешь роут как тебе написал Андрей выше:
```
 resource :locale, only: [] do
        member do
          get :switch
        end
      end
```
и этот хелпер у тебя будет доступен во всех вюхах и ты его подрубишь к переключателю, и будишь в качестве параметра передавать new_locale
https://github.com/hexlet-basics/hexlet-basics/blob/main/app/views/layouts/shared/_nav.html.slim#L76
и этот параметр у тебя будет приходить в экшен контроллера switch

2023-01-11 19:19 UTC, usernaimandrey commented on app/helpers/application_helper.rb
> +  def seo_for_paging(number_page, text)
> пытался править конфликт, не очень понимал механизм, подумал из-за того что в моей версии файла нет этого кода

тебе надо просто стянуть зминения, я обычно делаю так, если в удаленном репозитории появились изменения, обнавляю свой форк через интерфейс github, затем локально у себя на компе перехожу на ветку где работаю и делаю git pull origin main, если в чем то не прав @grozwalker поправь меня.

2023-01-11 20:32 UTC, grozwalker commented on app/helpers/application_helper.rb
> +  def seo_for_paging(number_page, text)
Можно и так) 
хотя вроде к форку привязан удалянный репозиторий и можно стянуть себе изменения сразу из него

https://docs.github.com/ru/get-started/quickstart/fork-a-repo

2023-01-12 01:21 UTC, askorutin26 commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
Спасибо за помощь! Теперь вроде собрал все вместе

2023-01-12 01:22 UTC, askorutin26 commented on app/helpers/application_helper.rb
> +  def seo_for_paging(number_page, text)
> > пытался править конфликт, не очень понимал механизм, подумал из-за того что в моей версии файла нет этого кода
> 
> тебе надо просто стянуть зминения, я обычно делаю так, если в удаленном репозитории появились изменения, обнавляю свой форк через интерфейс github, затем локально у себя на компе перехожу на ветку где работаю и делаю git pull origin main, если в чем то не прав @grozwalker поправь меня.

Понял, спасибо!

2023-01-12 01:59 UTC, askorutin26 commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
Созрел вопрос)
Проблема с тестами. 
![image](https://user-images.githubusercontent.com/66885436/211956613-cf218be7-ffc8-49b0-b0e2-41f4036eee90.png)

А с этой ошибкой сайт не открывается вообще
![Screenshot_2](https://user-images.githubusercontent.com/66885436/211956827-f2b4b442-157a-44e8-b505-55bea7131a8e.png)
Подскажите пожалуйста в какую сторону копать
Нашел ответ, что нужно выполнить rails webpacker:install , просит перезаписывать webpacker.yml and package.json

2023-01-12 02:32 UTC, usernaimandrey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
с тестами: 
попробуй перекомпилировать ассеты в коммандной строке введи bin/rails assets:clean, затем RAILS_ENV=test bin/rails assets:precompile
на всякий проверь файл https://github.com/Hexlet/hexlet-cv/blob/main/app/packs/entrypoints/application.js#L8
на предмет подключения стилей
если это не помогло зайди в директорию public/packs-test/css посмотри есть ли там файл application.сss - он должен создасться при компиляции, если есть то в этой же дирректории packs-test лежит manifest.json, посмотри там в самом начале должны строки:
```json
"application.css": "/packs-test/css/application.css"
 "application.js": "/packs-test/css/application.js"
```
если их нет добавь их руками - у меня такое было, их webpacker не добавлял почемуто

2023-01-12 02:35 UTC, usernaimandrey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
на счет второй ошибки: можешь показать свои роуты и менял ли ты код в контроллерах?

2023-01-12 03:05 UTC, askorutin26 commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
https://github.com/Hexlet/hexlet-cv/pull/390/commits/a16606318c7779db8627d5cf4ecbb12751194939#diff-959bc9abc46a55332bb64d5155a79323afa75a50ec1a2137ddd22d926f62c6c5

роуты, я менял scope locale, наверх перенес, не уверен что правильно текущий вариант

2023-01-12 03:09 UTC, askorutin26 commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
странно, теперь в pdf тесте такое
![image](https://user-images.githubusercontent.com/66885436/211966506-7d496a0f-651d-4b75-a302-698ab4aff8be.png)

2023-01-12 03:42 UTC, usernaimandrey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
> [a166063#diff-959bc9abc46a55332bb64d5155a79323afa75a50ec1a2137ddd22d926f62c6c5](https://github.com/Hexlet/hexlet-cv/commit/a16606318c7779db8627d5cf4ecbb12751194939#diff-959bc9abc46a55332bb64d5155a79323afa75a50ec1a2137ddd22d926f62c6c5)
> 
> роуты, я менял scope locale, наверх перенес, не уверен что правильно текущий вариант

у тебя  root 'home#index' покинул scope module :web, надо вернуть его, и ошибка с хомконтроллером должна уйти

2023-01-12 03:51 UTC, usernaimandrey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
на счет этой ошибки не могу сказать, первый раз такую вижу
посмотри какя версия вот этого гема wicked_pdf
в консоле введи bundle show тебе покажет все версии гемов проекта
я помню у него версия обновлялась и была запара этот тест как раз падал должна быть 2.6.3

2023-01-12 04:21 UTC, askorutin26 commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
да, версия 2.6.3 стоит
в manifest.json не было строчки с css, добавил, но все то же: 
`Webpacker can't find application.css in /mnt/d/hexlet-cv-main/public/packs/manifest.json.'

спасибо за подсказки, рут туда запихнул чтобы линтер не ругался что пустой скоп, а иначе 53 ошибки появляются, когда по другому сделано, пока тоже момент непонятный

2023-01-12 04:44 UTC, askorutin26 commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
увидел где ошибка, отличался файл webpacker.yml 
было source_path: app/javascript

2023-01-12 07:34 UTC, usernaimandrey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
Да надо эти строчки аернуть
source_path: app/packs
  source_entry_path: entrypoints
И ещё в секцию devserver
public:localhost:3035

2023-01-12 07:38 UTC, usernaimandrey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
> да, версия 2.6.3 стоит в manifest.json не было строчки с css, добавил, но все то же: `Webpacker can't find application.css in /mnt/d/hexlet-cv-main/public/packs/manifest.json.'
> 
> спасибо за подсказки, рут туда запихнул чтобы линтер не ругался что пустой скоп, а иначе 53 ошибки появляются, когда по другому сделано, пока тоже момент непонятный
Не увидел где у тебя пустой scope

2023-01-12 07:44 UTC, usernaimandrey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
> странно, теперь в pdf тесте такое ![image](https://user-images.githubusercontent.com/66885436/211966506-7d496a0f-651d-4b75-a302-698ab4aff8be.png)

Возможно это как раз из за не правильного конфига devserver в webpacker.yml

2023-01-12 16:08 UTC, askorutin26 commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
> > да, версия 2.6.3 стоит в manifest.json не было строчки с css, добавил, но все то же: `Webpacker can't find application.css in /mnt/d/hexlet-cv-main/public/packs/manifest.json.'
> > спасибо за подсказки, рут туда запихнул чтобы линтер не ругался что пустой скоп, а иначе 53 ошибки появляются, когда по другому сделано, пока тоже момент непонятный
> 
> Не увидел где у тебя пустой scope
```
scope '(:locale)', locale: /en|ru/ do
      end
```  
   Линтр ругается ```
Empty block detected.
  scope '(:locale)', locale: /en|ru/ do ...
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

2023-01-12 19:57 UTC, usernaimandrey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
так у тебя он же должен оборачивать все роуты
```ruby
scope '(locale)', locale: /en|ru/ do
    scope module: :web do
      root 'home#index'
      resources :vacancies, only: %i[index show]
      # FIXME: фикс дирекшенов с точками типа node.js, убрать, когда определимся, нужно ли будем валидировать направления и запретим указывать точки
      resources :vacancy_filters, only: %i[show], constraints: { id: %r{[^/]+} }, format: false, defaults: { format: 'html' } do
        collection do
          get :search, format: true
        end
      end
      resources :resumes do
        scope module: :resumes do
          resources :answers do
            member do
              patch :change_applying_state
            end
          end
          resources :pdfs, only: :show
          resources :comments
        end
      end
      resources :answers, only: [] do
        scope module: :answers do
          resources :comments
          resources :likes, only: %i[create destroy]
          resources :comments, only: %i[create update destroy]
        end
      end

      namespace :account do
        resources :resumes
        resources :vacancies
        resources :notifications, only: %i[index update]
        resource :newsletters, only: %i[edit update]
        resource :profile, only: %i[edit update show]
      end

      resources :users
      resources :pages

      scope module: :hooks do
        resource :sparkpost
      end

      namespace :admin do
        root 'home#index'
        resources :users, only: %i[index edit update]
        resources :resumes, only: %i[index edit update]
        resources :vacancies, only: %i[index edit update]
      end
    end
  end
```

2023-01-12 20:26 UTC, usernaimandrey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
еще тебе надо поидеи роуты devse тоже в scope local обернуть
```ruby
scope '(:locale)', locale: /en|ru/ do
    devise_for :users, skip: :omniauth_callbacks, controllers: { sessions: 'web/devise/sessions',
                                                                 registrations: 'web/devise/registrations' }
  end
  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'web/omniauth_callbacks' }
```
правильно Андрей @grozwalker

2023-01-12 21:25 UTC, askorutin26 commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
возможно кстати поэтому у меня и ошибки в тестах когда я пытался обернуть в locale, не все обернул
я посмотрел последнее измение в репозитории : https://github.com/Hexlet/hexlet-cv/commit/c3f28d42cfa5f79b7061f37a30b099eeb1cf2767 тесты упали с ошибкой 
`The asset "application.css" is not present in the asset pipeline.`
вот у меня тоже самое, и еще изменеия какие то, стоит подождать пока исправят? а потом сделать make setup еще раз?

2023-01-12 22:29 UTC, usernaimandrey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
да можешь стянуть изменения, и засетапить и взять некоторые изменения из этого пр https://github.com/Hexlet/hexlet-cv/pull/433/files
пока его не приняли, а именно добавить gem 'turbo-rails', еще там версия ruby в проекте поменялась теперь 3.2 тоже надо поставить и yarn убрали, теперь npm - соответственно ставь если нет и в корне npm install и все должно работать

2023-01-12 22:29 UTC, usernaimandrey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
я проверил у меня все good

2023-01-12 22:47 UTC, askorutin26 commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
понял, щас буду пробовать, спасибо за помощь!

2023-01-12 23:09 UTC, usernaimandrey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
не за что пиши если что

2023-01-13 20:37 UTC, usernaimandrey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
> да можешь стянуть изменения, и засетапить и взять некоторые изменения из этого пр https://github.com/Hexlet/hexlet-cv/pull/433/files пока его не приняли, а именно добавить gem 'turbo-rails', еще там версия ruby в проекте поменялась теперь 3.2 тоже надо поставить и yarn убрали, теперь npm - соответственно ставь если нет и в корне npm install и все должно работать

Слушай я забыл, теперь же на проекте Docker есть так что локально можно тебе и не ставить новую версию руби, разрабатывай через Docker

2023-01-13 22:01 UTC, askorutin26 commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
Да я уже установил, а с докером никогда не работал еще)

2023-01-14 11:18 UTC, fey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
не забывайте, что версию руби можно менять через asdf

2023-01-14 18:44 UTC, usernaimandrey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
> не забывайте, что версию руби можно менять через asdf

мне больше [rbenv](https://github.com/rbenv/rbenv) нравится, с asdf в плане ruby у меня почему то при компиляции исходников все время ошибка вылезала, но в rbenv как ни странно нет версии которая сейчас на проекте 3.2 есть только 3.2.0.preview и похоже придется asdf ставит)

2023-01-14 22:01 UTC, fey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
asdf удобен еще тем, что он nodejs поменяет (который тоже обновился в проекте).
Плюс есть еще другие языки =)

2023-01-14 22:08 UTC, usernaimandrey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
> asdf удобен еще тем, что он nodejs поменяет (который тоже обновился в проекте). Плюс есть еще другие языки =)

В Docker ноду надо тоже ставить через asdf или  nvm,  при конфиге который сейчас у меня вообще образ не зобрался, сказал что нода слишком старая, но я об этом в слаке написал и тебя тэгнул

2023-01-14 22:29 UTC, fey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
докер тут опционален, он был добавлен другим участником сообщества.
Поэтому ПРы велком.

2023-01-14 22:41 UTC, usernaimandrey commented on config/routes.rb
> +    scope '(:locale)', locale: /en|ru/ do
> докер тут опционален, он был добавлен другим участником сообщества. Поэтому ПРы велком.

Да это всегда пожайлуста
@fey в данный момент у меня не в docker не так проект не функционирует(после обновления) 
https://hexlet-students.slack.com/archives/C01VC4H877T/p1673651932656059

2023-01-19 22:52 UTC, closed without merging