add default value to resume_mail_enebled column in users
Hexlet/hexlet-cv pull request #406
Opened 2022-11-27 08:58 UTC by usernaimandrey

https://github.com/Hexlet/hexlet-cv/issues/373

2022-11-28 09:08 UTC, grozwalker commented on db/migrate/20221127083950_add_value_resume_mail_enabled_to_users.rb
> +    User.find_each do |user|
Но только тебе надо не перетереть тех людей, у кого false)
```
User.where(resume_mail_enabled: nil).update_all(resume_mail_enabled: true)
```

2022-11-29 01:12 UTC, usernaimandrey commented
> Надо немножко подправить миграцию.
> 
> И еще важная штука, на которую думаю ты еще не раз наткнешься, что надо проверять данные на проде и смотреть, чтобы все было валидно и твоя миграция пройдет.
> 
> Понятно, что при пр зайти в консоль проверить нельзя, но я просто к тому, что эту мысль надо всегда держать в голове

Понял, спасибо, исправлю

2022-11-29 01:21 UTC, usernaimandrey commented on db/migrate/20221127083950_add_value_resume_mail_enabled_to_users.rb
> +    User.find_each do |user|
Исправил, единственное там правило у Rubocop пришлось отключить, а то он ругался - update_all sckip model validation, ну это инлайн я думаю не страшно

2022-12-02 15:21 UTC, grozwalker requested changes

2022-12-02 15:21 UTC, grozwalker commented on db/migrate/20221127082921_change_resume_mail_enabled_default_value.rb
> +class ChangeResumeMailEnabledDefaultValue < ActiveRecord::Migration[6.1]
Прости, я проглядел в первый раз, но здесь ты ставишь дефолт в БД и это не очень хорошая практика, вот есть тред на этот счет https://gist.github.com/namreg/ba12ce0cc84ff34bab6b

2022-12-02 15:21 UTC, grozwalker commented on db/migrate/20221127082921_change_resume_mail_enabled_default_value.rb
> +class ChangeResumeMailEnabledDefaultValue < ActiveRecord::Migration[6.1]
Давай уберем эту миграцию и сделаем дефолты в моделе при инициилизации объекта

```
  def initialize(attrs = nil)
    defaults = {
      notification_enabled: true,
    }
    attrs_with_defaults = attrs ? defaults.merge(attrs) : defaults
    super(attrs_with_defaults)
  end
```
Это как пример

2022-12-04 09:52 UTC, usernaimandrey commented on db/migrate/20221127082921_change_resume_mail_enabled_default_value.rb
> +class ChangeResumeMailEnabledDefaultValue < ActiveRecord::Migration[6.1]
> Прости, я проглядел в первый раз, но здесь ты ставишь дефолт в БД и это не очень хорошая практика, вот есть тред на этот счет https://gist.github.com/namreg/ba12ce0cc84ff34bab6b

Понял спасибо за тред

2022-12-04 11:54 UTC, usernaimandrey commented
там вышла новая версия https://rubygems.org/gems/wkhtmltopdf-binary/versions/0.12.6.6, я ее в gemfile зафиксировал, потому что с 0.12.6.5 у меня тесты падали

2022-12-05 10:06 UTC, grozwalker commented on Gemfile
> +gem 'wkhtmltopdf-binary', '~> 0.12.6.6'
Это тогда пофиксим в другом ПРе, а так все супер. Спасибо большое

2022-12-05 10:13 UTC, grozwalker commented on test/models/user_test.rb
> +    attrs = {
ПС и еще мини оптимизация, чтобы такое не писать каждый раз руками (ну или в модели что-то измениться), лучше использовать FactoryBot, как например здесь https://github.com/Hexlet/hexlet-cv/blob/main/test/controllers/web/admin/users_controller_test.rb#L18

2022-12-06 14:45 UTC, grozwalker commented
Щикарно! Спасибо большое!

2022-12-06 14:46 UTC, grozwalker approved these changes

2022-12-06 14:46 UTC, merged

2022-12-06 17:50 UTC, usernaimandrey commented
> Щикарно! Спасибо большое!

не за что)