update docker file
Hexlet/hexlet-cv pull request #436
Opened 2023-01-15 22:58 UTC by usernaimandrey

с текущим конфигом докер образ не собирается, говорит что  версия nodejs  старая

2023-01-16 10:03 UTC, grozwalker requested changes

2023-01-16 10:03 UTC, grozwalker commented on Dockerfile
> +RUN mkdir /usr/local/nvm
Здесь это выглядит, как оверинжиниринг, у нас продакшн, мы точно в моменте не будет менять версии ноды.
Давай упростим конфиг просто поставим ноду

П.с. загляни в файл package.json и там прописана на какой версии ноды собирается в хероку, для билда и тестов нам надо взять точно такую же, чтобы разница в конфиге была минимальной (в идеале точно такая же)

Примерно как можно поставить ноду:
```
ENV NODE_VERSION 19.x

RUN curl -sL https://deb.nodesource.com/setup_${NODE_VERSION} | bash -

RUN apt-get install -y nodejs
```

2023-01-16 10:03 UTC, grozwalker commented on Dockerfile
> +RUN node -v
Это тоже надо убрать, у нас же продакшн сборка, там нечего особо смотреть. Но каждый слой увеличивает объем образа (в нашем случае не так актуально, тк мы заново собираем на хероку, но как хорошую практику надо знать)

2023-01-16 12:30 UTC, fey commented on Dockerfile
> +RUN mkdir /usr/local/nvm
Андрей, для прода не используется докер. Это все для разработки локально в контейнере.

2023-01-16 20:51 UTC, usernaimandrey commented on Dockerfile
> +RUN node -v
@grozwalker  поправил

2023-01-17 10:14 UTC, grozwalker requested changes

2023-01-17 10:14 UTC, grozwalker commented on Dockerfile
> +RUN apt-get update
Еще мини правка насчет этого. Посмотри вот здесь https://docs.docker.com/develop/develop-images/dockerfile_best-practices/

здесь есть несколько хороший практик: апдейт и инсталл писать вместе, удалять ненужные файлы после установки)

2023-01-17 10:14 UTC, grozwalker commented on Dockerfile
> +RUN mkdir /usr/local/nvm
сори, точно

2023-01-18 07:51 UTC, grozwalker commented on Dockerfile
>  COPY . .
Прости, почему-то не заметил в первый раз. 

А зачем здесь копирование файлов? Если это дев разработка, то мы же можем сбилдить образ, и потом второй командой уже поставить зависимости и накатить бд

А сейчас весь код лежит внутри образа. Можешь рассказать про профит такого подхода?

2023-01-18 07:56 UTC, grozwalker commented on Dockerfile
>  COPY . .
В общем я бы сделал вот так: https://github.com/hexlet-basics/hexlet-basics/blob/main/Dockerfile
https://github.com/hexlet-basics/hexlet-basics/blob/main/docker-compose.override.yml

Те в дев докерфайле настраивал среду, а установка зависмостей и все такое это было уже потом, когда стартую контейнеры

2023-01-18 07:58 UTC, grozwalker commented on Dockerfile
>  COPY . .
И плюс сейчас смотрю, что все равно надо будет потом запускать `make compose-setup`

2023-01-18 11:56 UTC, usernaimandrey commented on Dockerfile
>  COPY . .
> Прости, почему-то не заметил в первый раз.
> 
> А зачем здесь копирование файлов? Если это дев разработка, то мы же можем сбилдить образ, и потом второй командой уже поставить зависимости и накатить бд
> 
> А сейчас весь код лежит внутри образа. Можешь рассказать про профит такого подхода?

ну мне как то всегда думалось что надо весь проект в докер контейнер скопировать и потом уже засетапить

2023-01-18 13:08 UTC, usernaimandrey commented on Dockerfile
>  COPY . .
> И плюс сейчас смотрю, что все равно надо будет потом запускать `make compose-setup`

такой команды нет вроде) просто make compose-build и потом make compose

2023-01-18 13:11 UTC, usernaimandrey commented on Dockerfile
>  COPY . .
> В общем я бы сделал вот c такой идеей: https://github.com/hexlet-basics/hexlet-basics/blob/main/Dockerfile https://github.com/hexlet-basics/hexlet-basics/blob/main/docker-compose.override.yml
> 
> Те в дев докерфайле настраивал среду, а установка зависимостей и все такое это было уже потом, когда стартую контейнеры

пока не очень понимаю как это работает, если у нас кода приложения нет в контейнере как тогда засетапит, на каком этапе он должен там появится, если при старте контейнера то что мы при каждом старте будем сетапить приложение, вообщем мне непонятен этот момент.

2023-01-18 17:38 UTC, usernaimandrey commented on Dockerfile
>  COPY . .
Спасибо вроде понял)

2023-01-19 04:19 UTC, usernaimandrey commented on Dockerfile
>  COPY . .
вот такой конфиг но не могу понять почему то падают все тtсты хотя приложение работает нормально:
```
FROM ruby:3.2.0

ENV NODE_VERSION 19.x

RUN curl -sL https://deb.nodesource.com/setup_${NODE_VERSION} | bash -

RUN apt-get update \
  && apt-get install -y nodejs \
  && rm -rf /var/lib/apt/lists/*

ENV PROJECT_ROOT /app
RUN mkdir -p ${PROJECT_ROOT}

WORKDIR ${PROJECT_ROOT}

ENV BUNDLE_APP_CONFIG ${PROJECT_ROOT}/bundle/config
ENV GEM_HOME ${PROJECT_ROOT}/vendor/bundle
ENV BUNDLE_PATH ${GEM_HOME}
```

2023-01-19 04:24 UTC, usernaimandrey commented on Dockerfile
>  COPY . .
я за пушел посмотрите плиз, что может быть не так

2023-01-20 11:06 UTC, grozwalker approved these changes

2023-01-20 11:06 UTC, merged