Added translations and locale switch
Hexlet/hexlet-cv pull request #441
Opened 2023-01-20 01:09 UTC by askorutin26

Пересоздал PR 
старый: https://github.com/Hexlet/hexlet-cv/pull/390

Issues: #379 + #382

2023-01-20 10:10 UTC, grozwalker requested changes
По коду все супер, у меня лично никаких замечаний, остался небольшой вопрос с роутами

2023-01-21 02:47 UTC, askorutin26 commented on config/routes.rb
> +  scope '(:locale)', locale: /en|ru/ do
задал роуты с локалью для всего, почему то теперь при переходе на sign in/sign up язык меняется на en, но адрес остается http://localhost:3000/ru/users/sign_in

2023-01-23 12:00 UTC, grozwalker commented on config/routes.rb
> +  scope '(:locale)', locale: /en|ru/ do
а ты запушил последние изменения?

2023-01-23 12:01 UTC, grozwalker commented on config/routes.rb
> +  scope '(:locale)', locale: /en|ru/ do
Как один из вариантов, что у тебя там стоит девайс и его контроллеры наследуются нет от ApplicationController, а всяких своих, поэтому там не будет твоего LocaleConcern'а

2023-01-23 12:29 UTC, askorutin26 commented on config/routes.rb
> +  scope '(:locale)', locale: /en|ru/ do
> Как один из вариантов, что у тебя там стоит девайс и его контроллеры наследуются нет от ApplicationController, а всяких своих, поэтому там не будет твоего LocaleConcern'а

нет, последние изменения еще не пушил
включение local concern в контроллеры девайсов помогло , спасибо за помощь!

2023-01-23 13:32 UTC, closed without merging

2023-01-23 13:53 UTC, grozwalker commented on config/routes.rb
> +  scope '(:locale)', locale: /en|ru/ do
А почему-то закрыл его??? Или новый откроешь?

2023-01-23 13:56 UTC, askorutin26 commented on config/routes.rb
> +  scope '(:locale)', locale: /en|ru/ do
новый открою, не пойму что опять натворил, хотел сделать pull, так как не давало запушить
![image](https://user-images.githubusercontent.com/66885436/214057004-6af3912b-800b-4ea8-8d14-32d248d82835.png)