Markdown editor
Hexlet/hexlet-cv pull request #442
Opened 2023-01-20 11:41 UTC by Lodo4ka

подскажите как сделать маркдаун эдитор с байндингом полей формы? У trix редактора это реализовано через веб компопнент 

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/24316462/213687038-9b46e3e1-4e0d-4123-8c73-f181d3dd4ce9.png">

2023-01-23 13:51 UTC, grozwalker commented
Похоже ты делаешь не совсем то, что надо. Ты хочешь поставить визивиг редактор, а нам надо штуковина, которая бы вставляла маркдауyн, например, как здесь https://ru.hexlet.io/my/blog_posts/new

Мы сейчас используем пакет `bootstrap-markdown-fa5` (правда он уже староват и долго не обновлялся) и делаем как я говорил, создаем кастомный инпут, там подключаем  js и цсс

Как вариант еще нашел https://github.com/showdownjs/showdown и https://github.com/pandao/editor.md

2023-01-24 12:12 UTC, Lodo4ka commented
@grozwalker я разобрался как сделать, стоило только посмотреть на action_text и все стало понятно. Только походу надо будет добавить эту фичу к странице всех резюме 

<img width="1364" alt="image" src="https://user-images.githubusercontent.com/24316462/214288725-cfacb141-413c-4eb9-b1ab-a708d407432d.png">

2023-01-24 14:36 UTC, grozwalker commented
@acidmaksim в какие формы нужно добавить эту фичу?

2023-01-24 14:40 UTC, grozwalker requested changes
По логике все супер! Спасибо огромное. Немного подправить ошибки линтера и все будет готово. Ждем исправлений и будем бахать

2023-01-24 14:40 UTC, grozwalker commented on app/packs/entrypoints/application.js
> +    });
Пропустил пустую строку в конце) Она должна быть

2023-01-24 14:40 UTC, grozwalker commented on app/packs/entrypoints/application.js
> +import {Editor} from "@toast-ui/editor";
Здесь по-моему тоже должны быть пробелы между фигурными скобочками

2023-01-24 14:40 UTC, grozwalker commented
И пофиксить конфликты еще надо

2023-01-25 10:37 UTC, grozwalker commented
Вижу, что конфликты поправил, еще две маленькие ошибки линтера остались и будем деплоить

2023-01-25 11:05 UTC, Lodo4ka commented
@grozwalker исправил ошибки линтера

2023-01-25 14:17 UTC, grozwalker approved these changes

2023-01-25 14:36 UTC, grozwalker requested changes

2023-01-25 14:36 UTC, grozwalker commented on app/javascript/entrypoints/application.js
> +import 'bootstrap-icons/font/bootstrap-icons.css';
@Lodo4ka здесь ты добавил строку и она дублирует 13-ую строку, из-за этого падает сборка. Можешь пофиксить и оставить что-то одно?

2023-01-26 10:12 UTC, grozwalker approved these changes

2023-01-26 10:13 UTC, merged