Locale switch and translations
Hexlet/hexlet-cv pull request #445
Opened 2023-01-23 15:17 UTC by askorutin26

2023-01-24 14:31 UTC, grozwalker requested changes
Как по мне, так все супер! Пофикси тест и давай мерджить!

2023-01-24 18:05 UTC, askorutin26 commented
> Как по мне, так все супер! Пофикси тест и давай мерджить!

большую часть ошибок убрал, но еще остались 3, не понимаю как их фиксить, проблема как я понял с рутами в тестах и с дефолтной локалью, вариант который помог это в config/environment/test.rb добавить
```
config.action_mailer.default_url_options[:locale] = :en
routes.default_url_options[:locale] = :en
```
но ведь уже default_url_options существует
подскажите пожалуйста

![Screenshot_50](https://user-images.githubusercontent.com/66885436/214372097-187c57da-2d0f-4ed7-ba82-0bfd73fa0177.png)

2023-01-24 20:38 UTC, usernaimandrey commented
Попробуй в test_helpere прописать так:
```ruby
I18n.locale = ENV.fetch('RAILS_LOCALE', 'en').to_sym
Rails.application.routes.default_url_options[:locale] = I18n.locale
Rails.application.config.action_mailer.default_url_options[:locale] = I18n.locale
```
и тесты надо бы запускать чтобы у тебя тестировались обе локали
Makefile:
```
test:
  RAILS_LOCALE=ru bin/rails test 
  bin/rails test
```

если где то падают тесты можно еще попробовать передовать локаль явно:
```ruby
patch account_profile_path(@user, locale: I18n.locale), params: { user: attrs }
```

Еще было бы не плохо протестировать новый контроллер locales_controller

И я вижу еще одну проблему: сейчас если это выкатить все на прод то русскоязычному сегменту пользователей надо будет переключать все время локаль вручную с en на ru, потому что по дефолту стоит ангийская локаль.
Мне кажется тут надо бы сделать как на codebasics, определять локаль с помощью ipgeobase, и устанавливать и если не удалось определить то тогда ставить по дефолту, как вариант можно еще брать из заголовка http запроса, как думаешь @grozwalker?

2023-01-25 11:03 UTC, grozwalker commented
```
И я вижу еще одну проблему: сейчас если это выкатить все на прод то русскоязычному сегменту пользователей надо будет переключать все время локаль вручную с en на ru, потому что по дефолту стоит ангийская локаль.
Мне кажется тут надо бы сделать как на codebasics, определять локаль с помощью ipgeobase, и устанавливать и если не удалось определить то тогда ставить по дефолту, как вариант можно еще брать из заголовка http запроса, как думаешь @grozwalker?
```
Да, это проблема есть, круто, что заметил. @acidmaksim что будем делать? Это существенная проблема сейчас?

2023-01-25 11:30 UTC, askorutin26 commented
@usernaimandrey благодарю за помощь! тесты проходят, добавил вручную там, где падали

2023-01-26 08:00 UTC, grozwalker commented
@ashikov я там еще отписался, что нужен запуск тестов и для ЕН версии. Но вообще больше принятие этого ПР тормозит инфа, что пока непонятно что делат ьс этим, что по-дефолту будет открываться английская версия. @acidmaksim должен уточнить и прийти с ответом. Может быть мы сейчас поставим по-умолчанию ру версию, а потом докрутим определение локали

2023-01-31 14:08 UTC, acidmaksim commented
@askorutin26 делаем ру версию по дефолту, если она не стоит

2023-02-02 12:21 UTC, acidmaksim commented
@askorutin26 Кирилл добавил https://cv.hexlet.io/employment вот эту страницу, но она не переведена. Ее тоже нужно будет перевести, пока можешь воспользоваться переводчиком, а потом призовем кого нибудь, кто переведет это нормально

2023-02-02 16:02 UTC, askorutin26 commented
Дефолтную локаль оставлять ru? Или обратно на en, если теперь появился редирект?
Сейчас в пути url на английской версии отображается /en, на русской нет

2023-02-02 17:16 UTC, usernaimandrey commented
> Дефолтную локаль оставлять ru? Или обратно на en, если теперь появился редирект? Сейчас в пути url на английской версии отображается /en, на русской нет

по идеи можно английскую ставить потому что с редиректами все работает, @grozwalker какую локаль по дефолту оставляем?

2023-02-02 19:24 UTC, usernaimandrey commented
> Дефолтную локаль оставлять ru? Или обратно на en, если теперь появился редирект? Сейчас в пути url на английской версии отображается /en, на русской нет

можно в принципе по дефолту и ru поставить только логику надо немного поменять
```ruby
#locale_concern

def switch_locale(&)
    locale = params[:locale]&.present? ? extract_locale : :en 
    I18n.with_locale(locale, &)
  end

#web/aplication controller

def prepare_locale_settings
    if browser.bot?
      I18n.locale = params[:locale] || I18n.default_locale
      return
    end

    if current_page?(root_path) && !params[:locale]
      remembered_locale = session[:locale].presence
      if remembered_locale
        if remembered_locale.to_sym == I18n.default_locale
          redirect_to root_url(locale: I18n.default_locale), allow_other_host: true
        end
      else
        ru_country_codes = ['EN']
        if locale_from_accept_language_header == :en || ru_country_codes.include?(country_by_ip)
          redirect_to root_url(locale: nil), allow_other_host: true
        end
      end
    else
      session[:locale] = I18n.locale
    end
  end

module Web
  class LocalesController < Web::ApplicationController
    skip_before_action :prepare_locale_settings, only: [:switch]

    def switch
      locale = params[:new_locale]
      # redirect_path = requst.referer || root_path

      unless I18n.available_locales.include?(locale&.to_sym)
        redirect_back fallback_location: root_path(locale: I18n.default_locale)
        return
      end

      session[:locale] = locale

      if locale&.to_sym == I18n.default_locale 
        redirect_to root_path(locale:), allow_other_host: true
      else
        redirect_to root_path(locale: nil), allow_other_host: true
      end
    end
  end
end

# aplication_controller

def default_url_options
    { locale: I18n.locale == I18n.default_locale ? I18n.locale : nil }
  end

# test_helper
I18n.locale = ENV.fetch('RAILS_LOCALE', 'ru').to_sym
```

 и запуск тестов

```
RAILS_LOCALE=en bin/rails test
bin/rails test
```

2023-02-03 09:00 UTC, askorutin26 commented
пока оставил en, поменяю если что

2023-02-03 11:08 UTC, askorutin26 commented
коммит неправильно назвал, там перевод для страницы трудоустройство

2023-02-08 08:06 UTC, ssssank commented
@acidmaksim что тут делаем?

2023-02-09 12:45 UTC, fey commented
@grozwalker Кирилл ответил, что по дефолту ставим русский язык, а логика выбора языка такая же как на Хекслете.
Если эти требования ОК, то можно мержить ,если нет - то поправить и мержить)

2023-02-10 10:52 UTC, grozwalker requested changes

2023-02-10 10:52 UTC, grozwalker commented on app/controllers/web/application_controller.rb
> +    @country_by_ip = Geocoder.search(request.remote_ip).first&.country_code || 'EN'
Получается вот здесь надо поставить ру, чтобы по-дефолту был рф язык

2023-02-10 10:52 UTC, grozwalker commented on test/test_helper.rb
> +I18n.locale = ENV.fetch('RAILS_LOCALE', 'en').to_sym
и здесь

2023-02-13 09:55 UTC, grozwalker commented
@askorutin26 Поправь, пожалуйста, эти небольшие штуки и давай в ПР в прод!)

2023-02-13 23:17 UTC, askorutin26 commented
вроде все, поправил

2023-02-17 10:35 UTC, grozwalker approved these changes

2023-02-17 10:35 UTC, grozwalker commented
Спасибо!)

2023-02-17 10:41 UTC, merged