Setup redirect
Hexlet/hexlet-cv pull request #446
Opened 2023-01-28 02:55 UTC by usernaimandrey

2023-01-28 03:01 UTC, usernaimandrey commented
Пока сделал так чтобы посмотоеть как это работает, локально проверил редиректит на ru локаль, хочу развернуть на railway чтобы проверить

2023-01-28 03:02 UTC, usernaimandrey commented on app/controllers/web/application_controller.rb
>  end
собственн потом нужен будет только этот метод а остальное из этого реквеста https://github.com/Hexlet/hexlet-cv/pull/445

2023-01-28 03:03 UTC, usernaimandrey commented on app/controllers/web/application_controller.rb
> +  def prepare_locale_settings
собственн потом нужен будет только этот метод а остальное из этого реквеста https://github.com/Hexlet/hexlet-cv/pull/445

2023-01-28 11:56 UTC, grozwalker commented on config/locales/en.time.yml
> +      schema: '%m/%d/%Y'
Пустая строка!)

2023-01-28 11:58 UTC, grozwalker commented
Да, в целом норм все!

2023-01-28 11:58 UTC, grozwalker commented
А почему именно на рейлвэй? почему не локально?

2023-01-28 15:52 UTC, usernaimandrey commented
> А почему именно на рейлвэй? почему не локально?

Да хотел посмотреть, как это будет в боевом окружении работать, в целом это приём и код с  codebasics и он там нормально работает)
И локально вроде все норм
Тогда чуть позже переведу это из черновиках

2023-01-28 15:55 UTC, usernaimandrey commented
> А почему именно на рейлвэй? почему не локально?

Тогда как синхронизировать этот ПР с тем ПР просто оставить метод где локаль берётся по ip остальное все убрать?

2023-01-28 21:24 UTC, usernaimandrey commented
> А почему именно на рейлвэй? почему не локально?

https://demo-hexlet-cv.onrender.com
попробовал зайти так и с vpn вродевсе норм редиректит куды надо)
@grozwalker скажи тогда что оставить что удалить и как это все синхронизировать с другим ПР

2023-01-30 06:05 UTC, acidmaksim commented
@grozwalker по правильности переводов куда?
Например фильтры на другой странице нормальные, а здесь почему то так
![image](https://user-images.githubusercontent.com/77053797/215399362-ee9f2927-72df-4828-80a0-18d33edcc8f3.png)

2023-01-30 06:34 UTC, usernaimandrey commented
> @grozwalker по правильности переводов куда? Например фильтры на другой странице нормальные, а здесь почему то так ![image](https://user-images.githubusercontent.com/77053797/215399362-ee9f2927-72df-4828-80a0-18d33edcc8f3.png)

Так я не делал переводы, переводы же в другом пулл реквесте, думал мы как то синхронизируются, но если надо смогу добавить

2023-01-30 07:10 UTC, acidmaksim commented
@usernaimandrey Надо будет понять какие места не перевели и отдать нашим переводчикам

2023-01-31 03:59 UTC, usernaimandrey commented
> @usernaimandrey Надо будет понять какие места не перевели и отдать нашим переводчикам
добавил переводы, и добавил на render авторизацию через github в демку так что можно все проверить

2023-02-10 10:53 UTC, grozwalker requested changes
Пофикси, пожалуйста, конфликт

2023-02-10 12:05 UTC, usernaimandrey commented
> Пофикси, пожалуйста, конфликт

код из этого пр уже перешел вот в этот https://github.com/Hexlet/hexlet-cv/pull/445 там осталось только локаль поменять а этот я наверное в черновик переведу чтоб по ошибке не приняли

2023-02-10 12:06 UTC, grozwalker commented
Благодарю!

2023-02-17 11:36 UTC, closed without merging