fix displayed select
Hexlet/hexlet-cv pull request #451
Opened 2023-02-06 12:19 UTC by usernaimandrey

![Снимок экрана от 2023-02-06 15-18-06](https://user-images.githubusercontent.com/48034349/216969436-41f70775-90e3-4947-a2af-15655b73e44f.png)

востановил поис и сделал обрезку длинных тэгов

2023-02-07 11:35 UTC, grozwalker commented
Это скрин как стало?

2023-02-07 13:10 UTC, usernaimandrey commented
> Это скрин как стало?

Да, если надо могу это в демку залить что бы посмотреть можно было, у меня демка уже на рендаре развёрнута

2023-02-08 02:44 UTC, usernaimandrey commented
> Это скрин как стало?

Залил на ренедр https://demo-hexlet-cv.onrender.com/ru
Добавил в резюме длиннющий тэг отображается нормально
![Снимок экрана от 2023-02-08 05-41-30](https://user-images.githubusercontent.com/48034349/217415264-62486694-d07a-46bf-8ae0-1f4596ed95d0.png)

2023-02-08 09:11 UTC, grozwalker commented
Хм... а не слишком ли мало 20 символов? как буд-то может быть ничего не понятно, что скажешь?

2023-02-08 09:11 UTC, grozwalker requested changes

2023-02-08 09:11 UTC, grozwalker commented on app/helpers/application_helper.rb
> +      new_tag
В руби же последнее выражение по дефолту возвращается, нет смысла присваивать и потом возвращать

2023-02-08 18:22 UTC, usernaimandrey commented
> Хм... а не слишком ли мало 20 символов? как буд-то может быть ничего не понятно, что скажешь?

В целом я руководствовался тем что бы влезло Ruby-разработчик или Java-разрабртчик., но наверное да ты прав стоит увеличить

2023-02-09 07:28 UTC, grozwalker commented
Сделаешь тогда побольше?

2023-02-09 07:28 UTC, grozwalker commented
Пс а средствами цсс мы не можем решить эту проблему?

2023-02-09 07:29 UTC, grozwalker commented
И может тогда ограничить ввод супер длинных значений?

2023-02-09 07:36 UTC, usernaimandrey commented
> И может тогда ограничить ввод супер длинных значений?

Да сделаю, думаю можно и css, в принципе там стили selecta2 не дают растягивать дроп меню, просто длинные теги начинают переносится на другую строку

2023-02-09 08:19 UTC, usernaimandrey commented
> Пс а средствами цсс мы не можем решить эту проблему?

![image](https://user-images.githubusercontent.com/48034349/217755710-07e85db5-b13d-4c9e-a4fe-f45883fa4510.png)
вот так выглядет если 40 символов, просто переносится на новую строку

2023-02-09 08:37 UTC, usernaimandrey commented
увиличил до 40 символов, сделал ограничение на ввод на инпут

2023-02-10 10:56 UTC, grozwalker commented
Уточнил еще у продукта решение, у меня все-таки есть сомнения. 

Что ты прикрутил селект 2 -- круто и очень хорошо, но вот обрезать теги кажется как буд-то лишний код. Там проблема в одном направлении, видимо человек не думал, что надо через запятые вводить и надо добавить пояснение про это, возможно добавить валидацию и пофиксить данные этого человек и тогда код для обрезки писать и не нужно

2023-02-10 16:32 UTC, usernaimandrey commented
> Уточнил еще у продукта решение, у меня все-таки есть сомнения.
> 
> Что ты прикрутил селект 2 -- круто и очень хорошо, но вот обрезать теги кажется как буд-то лишний код. Там проблема в одном направлении, видимо человек не думал, что надо через запятые вводить и надо добавить пояснение про это, возможно добавить валидацию и пофиксить данные этого человек и тогда код для обрезки писать и не нужно

Добавил доп разделитель, ограничел инпут на 40 символов и добавил описание

2023-02-13 10:06 UTC, grozwalker commented
Итак, есть инфа как сделать получше. Давай уберем код, который обрезает данные на выводе, оставим валидацию 40 символов на ввод (каждого тэга), подпись, что надо вводить через запятую и селекте

2023-02-13 10:06 UTC, grozwalker commented
И фиксануть конфликт

2023-02-13 10:07 UTC, grozwalker commented
А я напишу миграцию, которая пофиксит данные у того человечка

2023-02-13 10:29 UTC, usernaimandrey commented on config/initializers/acts_as_taggable.rb
> +ActsAsTaggableOn.delimiter = [',', ' ']
А доп разделитель убрать?

2023-02-13 10:34 UTC, grozwalker commented on config/initializers/acts_as_taggable.rb
> +ActsAsTaggableOn.delimiter = [',', ' ']
Мне кажется да, там же люди пишут Back python

2023-02-13 10:35 UTC, usernaimandrey commented on config/initializers/acts_as_taggable.rb
> +ActsAsTaggableOn.delimiter = [',', ' ']
ок

2023-02-13 10:54 UTC, usernaimandrey commented on config/initializers/acts_as_taggable.rb
> +ActsAsTaggableOn.delimiter = [',', ' ']
вроде все)

2023-02-13 11:10 UTC, grozwalker commented on app/views/web/shared/_resume_form.html.slim
> +    = f.input :direction_list, input_html: { value: f.object.direction_list.to_s, maxlength: 40 }
а это разве не ограничит всю строку этой длинной? У меня получиться вписать два тега по 30 символов?

2023-02-13 13:10 UTC, grozwalker commented on app/views/web/shared/_resume_form.html.slim
> +    = f.input :direction_list, input_html: { value: f.object.direction_list.to_s, maxlength: 40 }
мне казалось ты уже это делал где-то... думаю в форме

2023-02-14 13:09 UTC, usernaimandrey commented on app/controllers/web/account/resumes_controller.rb
> +      render :new, status: :unprocessable_entity
без возврата токого статуса, было не возможно протестировать на невалидную длинну тэга, в тэстах возвращался статус 200

2023-02-14 13:14 UTC, usernaimandrey commented on app/controllers/web/account/resumes_controller.rb
> +      render :new, status: :unprocessable_entity
Провалидировал через ActiveFormModel, написал не большой валидатор, и добавил 2 теста

2023-02-14 13:17 UTC, usernaimandrey commented on app/controllers/web/account/resumes_controller.rb
> +      render :edit, status: :unprocessable_entity
по хорошему я бы везде бы это добавил, так на мой взгдяд это правильно, если сущность не создалась возвращаем 422

2023-02-17 09:42 UTC, grozwalker approved these changes
Поихали!

2023-02-17 09:42 UTC, merged

2023-02-17 13:01 UTC, usernaimandrey commented
> Поихали!

Погнали)