add migration archive old vacancies
Hexlet/hexlet-cv pull request #483
Opened 2023-02-21 22:53 UTC by usernaimandrey

2023-02-21 22:56 UTC, usernaimandrey commented
https://github.com/Hexlet/hexlet-cv/issues/480

2023-02-21 23:02 UTC, usernaimandrey commented
Написал пока мграцию которая архивирует вакансии старше 2-х недель, если двигаться в сторону автоматизации этого процесса то тогда нужен Redis и sidekick, ну и какой ни будь гем чтобы запускать задачу по крону например https://github.com/collectiveidea/delayed_job

2023-02-22 09:28 UTC, grozwalker requested changes
Давай переделаем миграцию примерно так:

```
vacancies = Vacancs.where(...)

vacancies.find_each do |vacancy|
   vacancy.archive!
end
```

2023-02-22 09:28 UTC, grozwalker commented on db/migrate/20230221221505_archive_vacancies_older_two_weeks.rb
> +    Vacancy.find_each do |vacancy|
Наконец-то ты дал повод что-то поправить у тебя!)

2023-02-22 09:28 UTC, grozwalker commented on db/migrate/20230221221505_archive_vacancies_older_two_weeks.rb
> +    Vacancy.find_each do |vacancy|
Смотри здесь какая фигня, получается ты выбираешь все вакансии и потом внутри цикла проверяешь надо ли архвивировать, те если вакансий 100к, то ты и выберешь все 100к, но подходящих для архивирования может быть всего 5 и тогда получается не оч оптимальная работа

Лучше сразу выбрать нужные вакансии, тогда выборка будет в бд и это гораздо проще для дальнейшей работы, а потом уже их архивировать без проверок

2023-02-22 09:28 UTC, grozwalker commented on db/migrate/20230221221505_archive_vacancies_older_two_weeks.rb
> +    Vacancy.find_each do |vacancy|
Конкретно в этой задаче у нас всего около 600 вакансий, поэтому в целом пофиг, но вообще лучше делать сразу правильнее

2023-02-22 09:28 UTC, grozwalker commented on db/migrate/20230221221505_archive_vacancies_older_two_weeks.rb
> +    Vacancy.find_each do |vacancy|
Еще момент о котором надо помнить, что вакансия может быть невалидной, поэтому в момент архивации будет выброщено исключение, поэтому этот момент надо проверять отдельно, либо убирать валидацию (но я проверил, вакансии валидные)

2023-02-22 09:28 UTC, grozwalker commented on db/migrate/20230221221505_archive_vacancies_older_two_weeks.rb
> +    Vacancy.find_each do |vacancy|
И еще одна штука о которой надо помнить, что если кол-во обрабатываемых записей слишком велико, то за время выполнения миграции (у нас в кубе это около 30 сек), то под убивается быстрее чем миграция выполняется, все откатывается и так происходит бесконечно (опять же не этот случай, но просто для справки)

2023-02-22 09:30 UTC, grozwalker commented
ПС по поводу автоматизации, давай напишем рейк таску, которая будет архивировать старые вакансии, а я потом настрою крон джобу в хероку

https://devcenter.heroku.com/articles/scheduler

2023-02-22 09:38 UTC, usernaimandrey commented on db/migrate/20230221221505_archive_vacancies_older_two_weeks.rb
> +    Vacancy.find_each do |vacancy|
> Наконец-то ты дал повод что-то поправить у тебя!)

))

2023-02-22 09:39 UTC, usernaimandrey commented on db/migrate/20230221221505_archive_vacancies_older_two_weeks.rb
> +    Vacancy.find_each do |vacancy|
> Смотри здесь какая фигня, получается ты выбираешь все вакансии и потом внутри цикла проверяешь надо ли архвивировать, те если вакансий 100к, то ты и выберешь все 100к, но подходящих для архивирования может быть всего 5 и тогда получается не оч оптимальная работа
> 
> Лучше сразу выбрать нужные вакансии, тогда выборка будет в бд и это гораздо проще для дальнейшей работы, а потом уже их архивировать без проверок

Об этом что-то не подумал, не оптимально поправлю)

2023-02-22 09:42 UTC, usernaimandrey commented on db/migrate/20230221221505_archive_vacancies_older_two_weeks.rb
> +    Vacancy.find_each do |vacancy|
> Еще момент о котором надо помнить, что вакансия может быть невалидной, поэтому в момент архивации будет выброщено исключение, поэтому этот момент надо проверять отдельно, либо убирать валидацию (но я проверил, вакансии валидные)

А вроде же все данные валидируются через activeformmodel в каком случае они могут быть не валидны, если только миграцию накатили и данные стали не консистентны?

2023-02-22 09:44 UTC, usernaimandrey commented
> ПС по поводу автоматизации, давай напишем рейк таску, которая будет архивировать старые вакансии, а я потом настрою крон джобу в хероку
> 
> https://devcenter.heroku.com/articles/scheduler

Хорошо

2023-02-22 10:28 UTC, grozwalker commented on db/migrate/20230221221505_archive_vacancies_older_two_weeks.rb
> +    Vacancy.find_each do |vacancy|
> А вроде же все данные валидируются через activeformmodel в каком случае они могут быть не валидны, если только миграцию накатили и данные стали не консистентны?

Ну бывает, что какие-то правила валидации добавляются уже позже и некоторые записи становятся невалидными

2023-02-28 08:10 UTC, ashikov commented
@grozwalker тыц

2023-03-01 11:16 UTC, grozwalker commented on db/schema.rb
> -ActiveRecord::Schema[7.0].define(version: 2022_11_27_083950) do
Хм... А чего это у тебя так файл схемы закожурило? РУбокоп здесь поменял? По идее он должен быть отключен для этого файла, тк он автогенериться и здесь постоянно будут двойные кавычки

2023-03-01 11:33 UTC, usernaimandrey commented on db/schema.rb
> -ActiveRecord::Schema[7.0].define(version: 2022_11_27_083950) do
да уменя стал запускатся по коммиту и он почемуто игнорирует правила

2023-03-01 21:42 UTC, usernaimandrey commented
fixed

2023-03-13 10:22 UTC, merged