new field contacts in resume
Hexlet/hexlet-cv pull request #501
Opened 2023-03-29 21:28 UTC by usernaimandrey

2023-03-30 08:39 UTC, grozwalker commented on db/migrate/20230329203609_add_contact_phone_to_resumes.rb
> +    add_column :resumes, :contact_phone, :string
Наверное моно было в одну миграцию забубенить (хотя и не важно)

2023-03-30 08:39 UTC, grozwalker commented on app/models/resume.rb
> +  validates :contact_email, 'valid_email_2/email': true
Может надо добавить еще и валидацию телефона?

2023-03-30 08:41 UTC, fey commented on app/forms/web/admin/resume_form.rb
> +  attrs = %i[state_event name hexlet_url github_url contact contact_email contact_phone summary skills_description awards_description english_fluency]
contact - тк это будет для телеги, его мб переименуем?

2023-03-30 20:24 UTC, usernaimandrey commented on app/forms/web/admin/resume_form.rb
> +  attrs = %i[state_event name hexlet_url github_url contact contact_email contact_phone summary skills_description awards_description english_fluency]
Обсудили с Андреем Г., добавил поле contact_telegram, астарое поле оставил написал что это дополнителные контакты - могут туда всякие ссылки на социалные сети присать

2023-03-30 20:24 UTC, usernaimandrey commented on app/models/resume.rb
> +  validates :contact_email, 'valid_email_2/email': true
да добавил

2023-03-30 20:25 UTC, usernaimandrey commented on app/forms/web/admin/resume_form.rb
> +  attrs = %i[state_event name hexlet_url github_url contact contact_email contact_phone summary skills_description awards_description english_fluency]
![Снимок экрана от 2023-03-30 22-54-46](https://user-images.githubusercontent.com/48034349/228955932-7e21fb13-17c8-4d89
![image](https://user-images.githubusercontent.com/48034349/228956048-d4dda804-a340-446b-90f4-1cccfb37a333.png)
-bf54-5835c522974a.png)

2023-03-31 07:23 UTC, usernaimandrey commented
@grozwalker @fey как сможете гляньте если все норм то бахнем

2023-03-31 08:46 UTC, grozwalker requested changes
Если валидация пропустит любой тлп, то можно поставить тудушку, что заменить на пакет (как на хекслете или даже лучше!) и мерджить. А доделать уже потом

2023-03-31 08:46 UTC, grozwalker commented on app/models/resume.rb
> +  validates :contact_phone, format: { with: /\A((\d{1}|\+\d{1})[- ]?)?(\(?\d{3}\)?[- ]?)?[\d\- ]{7,10}$\z/ },
а эта валидация пропустить какой-нибудь армянский или казахский номер? + 374 99 629302 например

2023-03-31 08:46 UTC, grozwalker commented on app/models/resume.rb
> +  validates :contact_phone, format: { with: /\A((\d{1}|\+\d{1})[- ]?)?(\(?\d{3}\)?[- ]?)?[\d\- ]{7,10}$\z/ },
Вообще это супер рукопашка как по мне и лучше использовать готовые пакеты

2023-03-31 08:46 UTC, grozwalker commented on app/forms/web/account/resume_form.rb
> +    contact_telegram summary
И если будешь править перенеси еще summary, а то оно думало скрыться от нас

2023-03-31 08:56 UTC, usernaimandrey commented on app/models/resume.rb
> +  validates :contact_phone, format: { with: /\A((\d{1}|\+\d{1})[- ]?)?(\(?\d{3}\)?[- ]?)?[\d\- ]{7,10}$\z/ },
> а эта валидация пропустить какой-нибудь армянский или казахский номер? + 374 99 629302 например

да пропустит любой  валидный номер формат +7 или 8

2023-03-31 09:34 UTC, fey commented
@usernaimandrey я бы демку посмотрел, как оно используется.

2023-03-31 10:44 UTC, usernaimandrey commented
> @usernaimandrey я бы демку посмотрел, как оно используется.

https://demo-hexlet-cv.onrender.com/ru

2023-03-31 11:01 UTC, usernaimandrey commented
> @usernaimandrey я бы демку посмотрел, как оно используется.

@fey докинул сейчас за делоится и можно посмотрет

2023-03-31 13:54 UTC, merged