locale separation
Hexlet/hexlet-cv pull request #502
Opened 2023-03-30 23:04 UTC by usernaimandrey

добавлю выборки еще в соответствии с локалью

2023-04-03 07:38 UTC, usernaimandrey commented
@grozwalker Андрюх как время будет глянь пожалуста

2023-04-03 16:35 UTC, grozwalker requested changes
В целом все норм, только поправить миграцию

2023-04-03 16:35 UTC, grozwalker commented on db/migrate/20230330213157_init_value_locale_to_user.rb
> +      user.locale = 'ru'
100 проц такая миграция зафейлиться, тк есть пользователи невалидные. Напиши здесь лучше запрос типа `User.update_all(locale: :ru)` это будет один запрос андейта и без проверки валидации. Нам это вроде и нужно

2023-04-03 17:03 UTC, usernaimandrey commented on app/repositories/resume_repository.rb
> +    scope :web, -> { order(id: :desc).published.with_locale.joins(:user).merge(User.permitted) }
ну да надо убрать

2023-04-03 17:03 UTC, usernaimandrey commented on app/controllers/web/account/resumes_controller.rb
> +    @resumes = current_user.resumes.with_locale
косяк)

2023-04-04 07:36 UTC, usernaimandrey commented on app/controllers/web/account/resumes_controller.rb
> +    @resumes = current_user.resumes.with_locale
@grozwalker Андрюх не некосяк если выводить по web пользователь не увидит свои резбме и вакансии которые в черновике

2023-04-04 08:25 UTC, usernaimandrey commented
Все поправил

2023-04-04 08:48 UTC, grozwalker approved these changes

2023-04-04 08:49 UTC, merged