career path client
Hexlet/hexlet-cv pull request #536
Opened 2023-04-28 12:36 UTC by usernaimandrey

2023-05-03 08:41 UTC, usernaimandrey commented
Единственное пока один контроллер тестами не покрыл, и пока нет ревью на шаг, но чтобы комит был не очень большой, хорошо бы сейчас что бы глянул

2023-05-04 13:30 UTC, usernaimandrey commented on db/migrate/20230502075107_create_career_step_members.rb
> +      t.integer :order, null: false
убрать ордер

2023-05-04 13:37 UTC, usernaimandrey commented on app/models/career/member.rb
> +  aasm :new_career_state, column: :new_career_state, timestamps: true do
поменять имя стайта на career_state

2023-05-04 13:42 UTC, usernaimandrey commented on app/models/career/member.rb
> +    state :finished
убрать переход из finished в archive, сделать одну стэйт машину и три стэйта in_progres finished archive

2023-05-04 14:07 UTC, usernaimandrey commented on app/models/career/step/member.rb
> +    state :working, initial: true
именовать стэйт одинаково с career_member

2023-05-04 14:26 UTC, ralder commented on app/views/layouts/shared/_nav.html.slim
> +        - unless current_or_guest_user.guest?
кажется есть предикат user_signed_in?

2023-05-04 14:33 UTC, ralder requested changes
остальное больше касается выборок - можно и потом пофиксить

2023-05-05 14:29 UTC, usernaimandrey commented on db/migrate/20230502075107_create_career_step_members.rb
> +      t.integer :order, null: false
может оставим это поле, у меня есть группировка по нему, если убрать как то сложно изебыватся приходится)
или может сделать связ не с шагом а с career_item

2023-05-05 15:12 UTC, corsicanec82 requested changes

2023-05-05 15:12 UTC, corsicanec82 commented on app/repositories/user_repository.rb
> +    scope :current_career, ->(career) { joins(:careers).where(careers: career) }
current_career по имени подумал что будет возвращена текущая карьера юзера.
А по коду получается другое.
Именование вводит в заблуждение.
Плюс кажется тут joins не нужен?
А также учитывая что юзера может быть несколько мемберов на один трек, на выходе может быть несколько одних и тех же карьер. Думаю уместно будет юзать distinct

2023-05-05 15:12 UTC, corsicanec82 commented on app/controllers/web/careers/members_controller.rb
> +    @current_item = @career_items.find_by(order: item_order)
Учитывая логику завязанную на ордер, я бы добавил как минимум валидацию на уникальность этому полю

2023-05-05 17:36 UTC, usernaimandrey commented on app/repositories/career_repository.rb
> +    scope :web, -> { where.not(career_members: { state: :archived }) }
с именем согласен косяк

 > и сделать через .merge(Career::Members.active)
тут еще finished выводится

2023-05-10 09:45 UTC, usernaimandrey commented
@corsicanec82, @ralder посмотрите пожайлуста

2023-05-11 11:32 UTC, corsicanec82 requested changes
Постарался выделить основные моменты. Остальное (выборки, именовавние и т.д.) если что потом отшлифуем

2023-05-11 11:32 UTC, corsicanec82 commented on app/models/career/member.rb
> +    return item.order == 1 if finished_step_member_count.zero?
item.order == 1
тут появляется привязка к использованию конкретных значений в поле order. А если первый шаг будет заархивирован, то нужно будет менять order у всех шагов и сдвигать что очень неудобно.
Думаю тут лучше будет получать first из отсортированных шагов и сравнивать их item == first_step

2023-05-11 11:32 UTC, corsicanec82 commented on app/models/career/member.rb
> +    return item.order == 1 if finished_step_member_count.zero?
также вместо finished_step_member_count.zero? можно заюзать unless career_step_members.finished.any?

2023-05-11 11:32 UTC, corsicanec82 commented on app/models/career/member.rb
> +    item.order <= finished_step_member_count + 1
тут тоже лучше уйти от количественных значений. Но в целом тут ещё сложнее, потому что количество конвертируется в order.
можно просто сравнить ордер у шагов
Получи вначале last_finished_step и дальше
item.order <= last_finished_step.order

2023-05-11 11:32 UTC, corsicanec82 commented on app/models/career/member.rb
> +    career_step_members.finished.size >= career.steps.size
тут может быть косяк, если пользователь завершил шаги которые на данные момент удалены из трека.
В таком случае завершенных мемберов может больше чем шагов в треке.

2023-05-11 11:32 UTC, corsicanec82 commented on app/models/career/step/member.rb
> +  aasm :step_state, column: :step_state do
Это стейт степ мембера же?
почему тогда называется step_state а не просто state?

2023-05-11 11:32 UTC, corsicanec82 commented on app/mutators/career/step/member_mutator.rb
> +  def self.find_or_create_step_member!(member, step, order)
тут что?

2023-05-11 11:32 UTC, corsicanec82 commented on app/repositories/career_repository.rb
> +    scope :with_not_archived_members, -> { where.not(career_members: { state: :archived }) }
лучше/привычнее without_archive_members

2023-05-11 11:32 UTC, corsicanec82 commented on db/schema.rb
> +    t.string "step_state", null: false
выше спросил о имени step_state

2023-05-11 11:32 UTC, corsicanec82 commented on db/schema.rb
> +    t.index ["career_member_id"], name: "index_career_step_members_on_career_member_id"
если не ошибаюсь то этот уже есть в t.index ["career_member_id", "career_step_id"]
Тут лучше у Сергея ещё уточнить

2023-05-11 12:19 UTC, usernaimandrey commented on app/models/career/member.rb
> +    item.order <= finished_step_member_count + 1
у шагов нет ордера

2023-05-11 12:20 UTC, usernaimandrey commented on app/models/career/member.rb
> +    item.order <= finished_step_member_count + 1
ордер есть только у item, а у шага может быть много items посколько шаг может принадлежать разным карьерным трекам

2023-05-11 12:31 UTC, corsicanec82 commented on app/models/career/member.rb
> +    item.order <= finished_step_member_count + 1
ну только вычисляй last_finished_item

2023-05-11 13:09 UTC, corsicanec82 commented on app/models/career/member.rb
> +    item.order <= finished_step_member_count + 1
От единицы надо уходить, потому что тога надо надо ставить ограничения для ордер, что их можно увеличивать только на 1 и т.д.

2023-05-11 13:10 UTC, corsicanec82 commented on app/models/career/member.rb
> +    item.order <= finished_step_member_count + 1
Получай items и бери следующий после finished.
И как вариант можно будет модифицировать условие так
item.order <= last_finished_item.order || item == next_item

2023-05-11 15:32 UTC, usernaimandrey commented on db/schema.rb
> +    t.index ["career_member_id"], name: "index_career_step_members_on_career_member_id"
@ralder Серега  подскажи

2023-05-12 10:03 UTC, ralder commented on db/schema.rb
> +    t.index ["career_member_id"], name: "index_career_step_members_on_career_member_id"
ага, Стас прав
если у тебя есть составной ключ, то индекс будет работать по всем его префиксам
т.е. если индекс [f1,f2,f3] то это равнозначно что также добавить индексы [f1] и [f1,f2]

или на sql, вот такие запросы будут его использовать:
where f1=x 
where f1=x and f2=y
where f1=x and f2=y and f3=z

а такие нет:
where f2=y and f3=z
where f3=z
where f2=y

(ps это касается только дефолтных btree индексов)

2023-05-12 10:08 UTC, ralder commented on app/controllers/web/admin/careers_controller.rb
> +    @users = @career.users.includes(:career_members).distinct
includes(:career_members) кажется теперь лишнее

2023-05-12 10:48 UTC, usernaimandrey commented on db/schema.rb
> +    t.index ["career_member_id"], name: "index_career_step_members_on_career_member_id"
а я правильно пнимаю что из за того что я создаю в этой миграции db/migrate/20230502075107_create_career_step_members.rb на 4 строку внешний ключ, автоматом образуется этот индекс

2023-05-12 11:55 UTC, corsicanec82 commented on db/schema.rb
> +    t.index ["career_member_id"], name: "index_career_step_members_on_career_member_id"
да. Его "автосоздание" можно отключить, раз потом ты создаёшь этот index_career_step_members_on_career_member_id_and_career_step_id

2023-05-12 12:50 UTC, usernaimandrey commented on app/models/career/member.rb
> +    first_item = career.items.first
отсортировать

2023-05-12 12:58 UTC, usernaimandrey commented on app/models/career/member.rb
> +    last_finished_item = career.items.with_finished_step_members(self).last
сортировка

2023-05-12 13:04 UTC, usernaimandrey commented on app/controllers/web/careers/members_controller.rb
> +    last_career_item = Career::Item.with_finished_step_members(resource_member).last
заменить на @career_iems.with_finidhed...

2023-05-12 13:16 UTC, usernaimandrey commented on app/controllers/web/careers/members_controller.rb
> +    last_career_item = Career::Item.with_finished_step_members(resource_member).last
написать метод для вычесления current_item(текущий шаг для прохождения) через первый активный item

2023-05-12 13:27 UTC, usernaimandrey commented on app/controllers/web/careers/members_controller.rb
> +    last_career_item = Career::Item.with_finished_step_members(resource_member).last
ели первого активного нет мы берем last_finished, 
items.where(order: last_finished&.order..).order().first

2023-05-12 13:30 UTC, usernaimandrey commented on app/models/career/member.rb
> +    item.order >= last_finished_item&.order || item.order < last_finished_item&.order
return item.order <= curent_item.oredr

2023-05-12 13:32 UTC, usernaimandrey commented on app/models/career/member.rb
> +    item.order >= last_finished_item&.order || item.order < last_finished_item&.order
остальную логику убрать

2023-05-12 13:35 UTC, usernaimandrey commented on app/mutators/career/step/member_mutator.rb
> +class Career::Step::MemberMutator
удалить

2023-05-12 13:40 UTC, usernaimandrey commented on app/models/career/member.rb
> +  def career_step_members_finished?
перенести вызов этого метода в стэйт машину

2023-05-12 13:43 UTC, usernaimandrey commented on app/models/career/member.rb
> +  end
обсодуть когда трек считается завершенным

2023-05-12 13:49 UTC, usernaimandrey commented on db/migrate/20230502075107_create_career_step_members.rb
> +      t.references :career_step, null: false, foreign_key: true
index: flase но лучше написать миграцию

2023-05-16 08:44 UTC, corsicanec82 requested changes

2023-05-16 08:44 UTC, corsicanec82 commented on app/controllers/web/careers_controller.rb
> +    @career_member = current_user.career_members.with_not_archived.last
тут же может отобразиться мембер из любой карьеры, а не только текущей. Так и задумывалось?

2023-05-16 08:44 UTC, corsicanec82 commented on app/models/career/member.rb
> +    last_finished_item = career.items.order(order: :asc).with_finished_step_members(self).last
last_finished_item - это значение стоит вычислять после гард экспрешн, так как оно может не понадобится

2023-05-16 08:44 UTC, corsicanec82 commented on app/models/career/member.rb
> +    last_finished_item
этот метод должен возвращать item который нужно проходить, то есть или активный или следующий после завершенного если активных нет. Если студент завершил шаг и не начал следующий, то метод can_show_step_body?(item) не позволит ему его даже показать.
Нужно согласовать логику.

2023-05-16 08:44 UTC, corsicanec82 commented on app/models/career/member.rb
> +    item.order <= current_item.order
а если студент только начинает проходить и у него нет ни активных не завершенных айтемов? То есть current_item будет nil
на синке мы же обсуждали логику метода current_item - должен возвращать то что надо проходить:
1. ищем активный айтем, если есть то возвращаем
2. если нет ищем последний завершенный и возвращаем следующий после него
3. если нет то возвращаем первый в треке

2023-05-16 08:44 UTC, corsicanec82 commented on app/models/career/member.rb
> +    next_item = career.items.order(order: :asc).where(order: item.order..).second
а если item nil

2023-05-16 08:44 UTC, corsicanec82 commented on app/mutators/career/step/member_mutator.rb
> +class Career::Step::MemberMutator
Всё ещё не удалил. Используется где-нибудь?

2023-05-16 08:44 UTC, corsicanec82 commented on app/repositories/career/item_repository.rb
> +    scope :with_active_step_members, ->(career_member) { with_step_members.merge(Career::Step::Member.active).where(career_step_members: { career_member: }) }
кажется можно упростить если where вызывать на степ мемберах. Нет?

with_step_members.merge(Career::Step::Member.finished.where(career_member:))

2023-05-16 08:44 UTC, corsicanec82 commented on app/repositories/career/member_repository.rb
> +    scope :with_not_archived, -> { where.not(state: :archived) }
Не то чтобы критично, но предлагаю согласовать именование.Тут with_not_archived, а в другом репозитории without_archive_members

2023-05-16 08:44 UTC, corsicanec82 commented on db/schema.rb
>      t.index ["career_id"], name: "index_career_items_on_career_id"
Этот индекс похоже тоже не обязательно добавлять

2023-05-16 08:44 UTC, corsicanec82 commented on db/migrate/20230515080525_remove_index_from_career_step_members.rb
> +    remove_index :career_step_members, :career_step_id
Похоже ты не тот индекс снёс. В ревью речь шла об индексе index_career_step_members_on_career_member_id

2023-05-16 08:54 UTC, usernaimandrey commented on app/models/career/member.rb
> +    first_item = career.items.first
этого уже нет этот метод теперь выглядит так
```
 def can_show_step_body?(item)
    item.order <= current_item.order
  end
```

2023-05-16 08:58 UTC, corsicanec82 commented on app/models/career/member.rb
> +    first_item = career.items.first
> этого уже нет этот метод теперь выглядит так
> 
> ```
>  def can_show_step_body?(item)
>     item.order <= current_item.order
>   end
> ```

Андрей, обрати внимание, что ты комментируешь не последнее ревью а то что было 4 дня назад

2023-05-16 09:03 UTC, usernaimandrey commented on app/models/career/member.rb
> +    first_item = career.items.first
а прошу прощения

2023-05-16 13:42 UTC, corsicanec82 commented on app/controllers/web/careers/members_controller.rb
> +    item_order = params[:step] || career_item&.order || @career_items.first.order
так это не сработает find_by(order: params[:step])
не получится искать по ордеру передавая туда номер шага
@career_items[ params[ :step ]  + 1 ] - тут по идее -1 минус один должно быть?

2023-05-16 13:45 UTC, usernaimandrey commented on app/controllers/web/careers/members_controller.rb
> +    item_order = params[:step] || career_item&.order || @career_items.first.order
да - 1

2023-05-16 14:13 UTC, usernaimandrey commented on app/controllers/web/careers/members_controller.rb
> +    item_order = params[:step] || career_item&.order || @career_items.first.order
> так это не сработает find_by(order: params[:step]) не получится искать по ордеру передавая туда номер шага @career_items[ params[ :step ] + 1 ] - тут по идее -1 минус один должно быть?

не получится это семантически не верно? так то все работает

2023-05-17 14:03 UTC, usernaimandrey commented on app/controllers/web/careers/members_controller.rb
> +    return @career_items[params[:step].to_i - 1].order if params[:step].present?
params[:step].to_i - 1 - в отельную переменную

2023-05-17 14:07 UTC, usernaimandrey commented on app/controllers/web/careers/members_controller.rb
> +    resource_member.current_item&.order || @career_items.first.order
возвращать только resource_member.current_item.order

2023-05-17 14:21 UTC, usernaimandrey commented on app/models/career/member.rb
> +    return first_active_item if first_active_item.present?
убрать present?

2023-05-17 14:25 UTC, usernaimandrey commented on app/models/career/member.rb
> +    return career_items.where(order: last_finished_item&.order..).second if last_finished_item.present?
убрат & и present?

2023-05-17 14:31 UTC, usernaimandrey commented on app/models/career/member.rb
>        transitions from: %i[active], to: :finished, guard: :career_step_members_finished?
:mark_as_archived - переименовать

2023-05-17 14:44 UTC, usernaimandrey commented on app/controllers/web/careers_controller.rb
> +    @user_career_members = current_user.career_members.includes(:career).without_archive_members
поменять контроллер и урл преренести в контроллер  career_members index

2023-05-17 14:57 UTC, usernaimandrey commented on app/views/web/careers/members/show.html.slim
> +        = link_to career_member_path(resource_career, resource_member, step: item.order), class: ['nav-link px-3', @career_item&.order == item.order ? 'active' : ''] do
передавать index + 1 в место item.order

2023-05-18 06:58 UTC, usernaimandrey commented on app/models/career/member.rb
> +    return first_active_item if first_active_item.present?
убрал

2023-05-18 06:59 UTC, usernaimandrey commented on app/controllers/web/careers/members_controller.rb
> +    resource_member.current_item&.order || @career_items.first.order
поправил

2023-05-18 07:47 UTC, usernaimandrey commented on app/models/career/member.rb
> +    return career_items.where(order: last_finished_item&.order..).second if last_finished_item.present?
сделал вот так
```
def next_item(items)
    last_finished_item = items.with_finished_step_members(self).last
    items.where(order: last_finished_item.order..).second if last_finished_item
end
```
условие оставил поту как если last_finished == nil  эта выборка `items.where(order: last_finished_item.order..)` выдает всех  items

2023-05-18 07:51 UTC, usernaimandrey commented on app/models/career/member.rb
>        transitions from: %i[active], to: :finished, guard: :career_step_members_finished?
преименовал event  на archive

2023-05-18 08:17 UTC, corsicanec82 commented on app/models/career/member.rb
> +    return career_items.where(order: last_finished_item&.order..).second if last_finished_item.present?
так мы же не так говорили
смотри сигнару метода, которую ты выше описал def next_item(item). Не items!!!

```
def next_item(item)
   career.items.where(order: item.order..).order(order: :asc).second
end
```
и этот метод будет возвращать следующий или nil если следующего нет

А в коде выше юзаешь его, например так.
```
def current_item
  ...
  next_item(last_finished_item) || career_items.first if last_finished_item
  career_items.first
end
```

2023-05-18 09:23 UTC, usernaimandrey commented on app/models/career/member.rb
> +    return career_items.where(order: last_finished_item&.order..).second if last_finished_item.present?
понял, принял исправил

2023-05-18 09:37 UTC, usernaimandrey commented on app/controllers/web/careers/members_controller.rb
> +    return @career_items[params[:step].to_i - 1].order if params[:step].present?
вынес в отдельную переменную у меня получилось так
```
def item_order
    step = params[:step].to_i - 1 
    return @career_items[step].order if step.positive?

    resource_member.current_item.order
  end
```
 если params[:step] == nil то он при вызове to_i превращается в 0

2023-05-18 09:39 UTC, corsicanec82 commented on app/controllers/web/careers/members_controller.rb
> +    return @career_items[params[:step].to_i - 1].order if params[:step].present?
что планируешь делать с этим?

2023-05-18 09:50 UTC, usernaimandrey commented on app/controllers/web/careers/members_controller.rb
> +    return @career_items[params[:step].to_i - 1].order if params[:step].present?
мне кажется так не очень, превый вариант думаю лучше только present? уберу

2023-05-18 09:53 UTC, corsicanec82 commented on app/controllers/web/careers/members_controller.rb
> +    return @career_items[params[:step].to_i - 1].order if params[:step].present?
Не понял. Что именно не очень?

2023-05-18 09:54 UTC, corsicanec82 commented on app/controllers/web/careers/members_controller.rb
> +    return @career_items[params[:step].to_i - 1].order if params[:step].present?
и кстати step = это не step

2023-05-18 11:41 UTC, corsicanec82 commented on app/controllers/web/careers/members_controller.rb
> +    return @career_items[params[:step].to_i - 1].order if params[:step].present?
> step.positive? ну мне вот это не совсем нравится если так смотришь первый раз не совсем понятно почему order может быть отрицательным

так а зачем тогда добавлял использование positive. Этот метод и не нужен был


> да это item_order наверное

скорее item_index

---

Также стоит подумать над логикой, что будет происходить при попытке открытия шага которого нет. Тут или 404 выбрасывать или открывать какой-то шаг, как например сделано на хекслете. Там кажется первый открывается в таком случае.
Вот например так можно сделать в контроллере

```
  item_index = params[:step].to_i - 1
  @career_item = @career_items[item_index]
  # ну или вместо @career_items.first resource_member.current_item тогда будет кидать на текущий если не найден или недоступен
  @career_item = @career_items.first if !@career_item || !resource_member.can_show_step_body?(@career_item)
```

2023-05-18 12:23 UTC, usernaimandrey commented on app/controllers/web/careers_controller.rb
> +    @user_career_members = current_user.career_members.includes(:career).without_archive_members
убрал эту логику в контроллер к юзеру,  думаю так правельнее потому как мемберы относятся помимо карьеры еще и к юзеру и в своем аккаунте он будет видеть какие треки он проходит

2023-05-18 12:31 UTC, usernaimandrey commented on app/controllers/web/careers/members_controller.rb
> +    return @career_items[params[:step].to_i - 1].order if params[:step].present?
params[:step].to_i - 1 тут надо учитывать что если шага нет то выражение вернет     - 1 и возмется последний элемент в массиве items или я ошибаюсь

2023-05-18 12:34 UTC, corsicanec82 commented on app/controllers/web/careers_controller.rb
> +    @user_career_members = current_user.career_members.includes(:career).without_archive_members
ok

2023-05-18 12:35 UTC, corsicanec82 commented on app/controllers/web/careers/members_controller.rb
> +    return @career_items[params[:step].to_i - 1].order if params[:step].present?
угу так и будет.
Дорабатывай, не я же пишу код в твоём ПРе )

2023-05-18 20:58 UTC, usernaimandrey commented on app/controllers/web/careers/members_controller.rb
> +    return @career_items[params[:step].to_i - 1].order if params[:step].present?
вынес логику определения career_item в отдельный метод
```
helper_method :career_item

  def show
    authorize resource_member
    @career_items = resource_career.items.order(order: :asc)
    @career_step_members = resource_member.career_step_members.ordered

    @career_step = career_item.career_step
    @career_step_member = resource_member.career_step_members.find_or_create_by!(career_step: @career_step)
  end

  def career_item
    return resource_member.current_item unless params[:step]

    item_index = params[:step].to_i - 1

    career_item = @career_items[item_index]

    return career_item if career_item

    @career_items.first
  end
```

2023-05-19 09:17 UTC, usernaimandrey commented on app/controllers/web/careers/members_controller.rb
> +    return @career_items[params[:step].to_i - 1].order if params[:step].present?
сделать привтным и не делать хелпером

2023-05-19 09:38 UTC, usernaimandrey commented on app/views/web/careers/members/show.html.slim
> +        = link_to career_member_path(resource_career, resource_member, step: index + 1), class: ['nav-link px-3', career_item.order == item.order ? 'active' : ''] do
уйти от индексов

2023-05-19 09:43 UTC, corsicanec82 requested changes

2023-05-19 09:43 UTC, corsicanec82 commented on app/views/web/users/_careers.html.slim
> +        -if career_member&.finished?
& лишний помоему

2023-05-19 09:43 UTC, corsicanec82 commented on app/views/web/careers/members/show.html.slim
> +          - if @career_step_members[index]&.finished?
из-за index при добавлении шагов или удалении - отображение поплывёт. Используй подготовленный хеш в контроллере by_step_id
index можно будет выпилить

2023-05-19 09:43 UTC, corsicanec82 commented on app/controllers/web/careers/members_controller.rb
> +    return career_item if career_item
можно упростить 
career_item || @career_items.first
и стоит подумать над использованием resource_member.can_show_step_body?(career_item)
чтобы пользователь не мог открыть шаг к которому нет доступа

2023-05-19 09:43 UTC, corsicanec82 commented on app/repositories/career/step/member_repository.rb
> +    scope :ordered, -> { joins(career_step: :career_items).merge(Career::Item.order(order: :asc)) }
order(order: :asc)
можно для модели item сделать тоже скоуп ordered. И переиспользовать его

2023-05-19 10:33 UTC, usernaimandrey commented on app/repositories/career/step/member_repository.rb
> +    scope :ordered, -> { joins(career_step: :career_items).merge(Career::Item.order(order: :asc)) }
добавил scope

2023-05-19 10:34 UTC, usernaimandrey commented on app/controllers/web/careers/members_controller.rb
> +    return career_item if career_item
добавил так
```
def career_item
    return resource_member.current_item unless params[:step]

    item_index = params[:step].to_i - 1

    if @career_items[item_index] && resource_member.can_show_step_body?(@career_items[item_index])
      @career_items[item_index]
    else
      @career_items.first
    end
  end
```

2023-05-19 10:34 UTC, usernaimandrey commented on app/views/web/careers/members/show.html.slim
> +          - if @career_step_members[index]&.finished?
в контроллере сделал @career_step_members_by_step_id = career_step_members.index_by(&:career_step_id)
и во вюхе 
- if @career_step_members_by_step_id[item.career_step_id]&.finished?

2023-05-19 11:02 UTC, corsicanec82 approved these changes
критических замечаний у меня нет, есть местами моменты с использованием скоупов, именованием, но это можно потом улучшить и доработать.
Заапрувил.

2023-05-19 11:02 UTC, corsicanec82 commented on app/repositories/career/step/member_repository.rb
> +    scope :ordered, -> { joins(career_step: :career_items).merge(Career::Item.order(order: :asc)) }
а почему не использовал?

2023-05-19 11:26 UTC, ralder commented on app/controllers/web/careers/application_controller.rb
> +    f(:error)
TODO переименовать

2023-05-19 11:27 UTC, ralder commented on app/controllers/web/careers/members_controller.rb
> +  end
TODO унести логику определения следущего итема в модель

2023-05-19 11:31 UTC, ralder approved these changes

2023-05-19 11:39 UTC, usernaimandrey commented on app/repositories/career/member_repository.rb
> +    scope :without_archive_members, -> { where.not(state: :archived) }
TODO убрать ипользование строк из условия

2023-05-19 11:50 UTC, merged