Add filter resume
Hexlet/hexlet-cv pull request #542
Opened 2023-05-03 22:01 UTC by usernaimandrey

2023-05-03 22:09 UTC, usernaimandrey commented
У резюме есть фильтр - резюме без рекомендаций, он теперь работать не будет так как все резюме идут с рекомендацией от Tota AI - добавил фильтр

2023-05-04 07:39 UTC, ralder commented on app/views/web/home/index.html.slim
> +  = filter_link(t('.without_answers_human'), { answers_count_eq: 1, answers_user_id_eq: @user.id }, class: 'nav-item nav-link')
здесь наверно нужно <= 1

2023-05-04 07:40 UTC, ralder commented on app/controllers/web/home_controller.rb
> +    @user = User.find_by(email: ENV.fetch('EMAIL_SPECIAL_USER'))
это же бот, так и надо его так именовать, и вообще бы сделать его поулчение через хелпер чтобы метод его получения был в одном месте

2023-05-04 07:41 UTC, ralder commented on app/models/resume/answer.rb
> +    %w[user]
кажется это лишнее

2023-05-04 07:42 UTC, ralder requested changes
и я бы еще добавил форму где описал все разрешенный параметры - шоб напрямую не давать доступ пользователем к рансаку с любыми параметрами

2023-05-04 08:12 UTC, usernaimandrey commented on app/views/web/home/index.html.slim
> +  = filter_link(t('.without_answers_human'), { answers_count_eq: 1, answers_user_id_eq: @user.id }, class: 'nav-item nav-link')
тогда вот так можно answers_count_in: [0, 1] а то такую форму <= 1 он что то не хочет воспринимат

2023-05-05 08:57 UTC, usernaimandrey commented
@ralder  Серег бутет время глянь пожалйста я тут вроде поправил

2023-05-10 09:40 UTC, usernaimandrey commented
> @ralder Серег бутет время глянь пожалйста я тут вроде поправил

@ralder Серег глянь пожалйста

2023-05-12 09:36 UTC, ralder requested changes
1) лучше не привязываться конкретно к "open_ai", поэтому лучше назвать просто ai_bot, или может быть еще более понятнее что это за обект ai_bot_user
2) консерн лежит в controllers/concerns а используется в сервисах - лучше не смешивать... вообще кажется просто добавить метод в хелпер было бы ок и без консернов

2023-05-12 09:37 UTC, ralder commented on app/forms/web/resumes/search_form.rb
> +    ATTRIBUTES.each do |attribut|
typo

2023-05-12 10:20 UTC, usernaimandrey commented
> 1. лучше не привязываться конкретно к "open_ai", поэтому лучше назвать просто ai_bot, или может быть еще более понятнее что это за обект ai_bot_user
> 2. консерн лежит в controllers/concerns а используется в сервисах - лучше не смешивать... вообще кажется просто добавить метод в хелпер было бы ок и без консернов

готово

2023-05-12 13:37 UTC, ralder approved these changes

2023-05-12 13:37 UTC, ralder commented on app/services/resume_auto_answer_service.rb
> +  extend ApplicationHelper
поставь TODO: чтобы переделать без этого

2023-05-12 14:41 UTC, usernaimandrey commented on app/services/resume_auto_answer_service.rb
> +  extend ApplicationHelper
а как этот метод будет доступен в сервисном классе если extend не сделать?

2023-05-12 17:29 UTC, ralder commented on app/services/resume_auto_answer_service.rb
> +  extend ApplicationHelper
не знаю) может быть чтото типа через метод какого то класса HelperX.ai_bot_user
но так точно плохо - закидывать все методы хелепера изза одного

2023-05-15 07:22 UTC, merged