Improve resume skills description
Hexlet/hexlet-cv pull request #744
Opened 2024-05-08 10:25 UTC by eKulshan

resolves #711

2024-05-08 10:29 UTC, eKulshan commented
resolves #711

2024-05-08 10:52 UTC, fey commented
Задеплойте пожалуйста демку, чтобы посмотреть визуально

2024-05-08 12:39 UTC, fey commented
@eiKulshan а что за файлы нужно добавлять? По идее деплой на рендер должен работать обычным способом,  там есть поддержка рельсы. Посмотрите в ридми инструкцию по деплою https://github.com/Hexlet/hexlet-cv#deploy-to-rendercom

2024-05-17 16:13 UTC, usernaimandrey commented on app/models/resume.rb
> +  validates :skills_description, length: { maximum: 250 }, presence: true, unless: :draft?
Валидация строчкой ниже дублируется presence валидацию

2024-05-17 16:28 UTC, usernaimandrey commented on db/migrate/20240508043924_update_resume_skill_description.rb
> +  end
Валидация на длину на уровне базы данных я бы не стал добавлять, а обошёлся только на уровне модели, тем более на уровне модели она условная, а на уровне базы сейчас нет,  пользователь в драфт воткнет длинную строку и страница упадёт с ошибкой

2024-05-17 16:30 UTC, usernaimandrey commented
Ну и тест добавить, что если строка длинная резюме не сохранится

2024-05-27 12:05 UTC, corsicanec82 requested changes

2024-05-27 12:05 UTC, corsicanec82 commented on app/models/resume.rb
>    validates :skills_description, presence: true, unless: :draft?
одна валидация лишняя

2024-05-27 12:05 UTC, corsicanec82 commented on db/migrate/20240508043924_update_resume_skill_description.rb
> +  end
пожалуй да, тут не обязательно добавлять ограничение, достаточно валидации в модели

2024-05-28 10:02 UTC, eKulshan commented
Спасибо за ревью!
Внес правки.
Не совсем уверен в реализации презентера и валидации.
И не уверен что тест удачно написан.
Если можно улучшить, подскажите как, исправлю

2024-06-08 21:43 UTC, usernaimandrey commented on app/presenters/resume_presenter.rb
> +  def skills
У модели резюме уже есть метод skills, через который работает гем ActsAsTaggableOn, тут ты его переопределил, нужно выбрать другое имя метода

2024-06-08 21:46 UTC, usernaimandrey commented on test/controllers/web/account/resumes_controller_test.rb
> +    attrs[:skills_description] = 'Invalid_skill_lenght' * 2
Если тестируешь два разных кейса то лучше разделить на два теста

2024-06-08 21:48 UTC, usernaimandrey commented on test/controllers/web/account/resumes_controller_test.rb
> +    post(account_resumes_path, params:)
в параметры добавь пожалуйста locale, что бы тест прогонялся для двух локалей
```ruby
post account_resumes_path, params:, locale: I18n.locale
```

2024-06-08 21:52 UTC, usernaimandrey commented on db/schema.rb
> +    t.text "skills_description", limit: 250
прогони плиз еще раз миграцию, в схеме осталась валидация на длину на уровне базы

2024-06-08 21:55 UTC, usernaimandrey commented on app/models/resume.rb
> +    return unless skills.size > 10 || skills.any? { |element| element.size > 25 }
почему  или, должно же быть и - длинна скила не больше 25 и не больше 10 скилов

2024-10-03 12:35 UTC, fey commented
@eKulshan как успехи? Продолжите работу?

2024-11-28 17:41 UTC, beherit197777 commented
взял в работу

2025-07-10 10:44 UTC, closed without merging