add cancel process from vacancies
Hexlet/hexlet-cv pull request #760
Opened 2024-07-07 22:36 UTC by usernaimandrey

2024-07-07 22:38 UTC, usernaimandrey commented
https://github.com/Hexlet/hexlet-cv/issues/757

2024-07-11 07:55 UTC, HelenOne commented
Can you please deploy so we can check it visually?

2024-07-16 11:00 UTC, fey commented
@usernaimandrey zadeploy demo plz -)

2024-07-19 11:22 UTC, fey commented
@usernaimandrey Is it ready and can be reviewed? Or will there be more tweaking to be done?

2024-07-19 12:30 UTC, usernaimandrey commented
> @usernaimandrey Is it ready and can be reviewed? Or will there be more tweaking to be done?

Привет! Сегодня работу с нотификациями еще закину и все

Задеплоить демку куда то не обещаю так как бесплатные периоды на рендере и  railway  закаончились

2024-07-20 08:04 UTC, usernaimandrey commented
Можно ревьюить)

2024-07-22 11:30 UTC, fey commented
@usernaimandrey визуально вроде ок.

2024-07-22 11:30 UTC, fey commented
@usernaimandrey наверное в фикстуры можно добавить отклоненнуюв акансию + уведомление

2024-07-22 11:34 UTC, usernaimandrey commented
> @usernaimandrey наверное в фикстуры можно добавить отклоненнуюв акансию + уведомление

Приветы добавил https://github.com/Hexlet/hexlet-cv/pull/760/files#diff-2c100dd4ab7c69690757b0077c937e0bd0b6df3f5071c5cc2049ac4e56fa47e7

2024-07-25 09:51 UTC, corsicanec82 requested changes

2024-07-25 09:51 UTC, corsicanec82 commented on app/controllers/web/admin/vacancies_controller.rb
> +  def vacancy_form
не совсем корректные названия для оберток классов, так как можно подумать что они уже возвращают объект. На самом деле выглядит несколько лишней обёрткой, плюс усложняется чтение кода, приходится заглядывать в сам метод.
Тоже самое по поводу vacancy_service
Используй имена классов напрямую там где они нужны

2024-07-25 09:51 UTC, corsicanec82 commented on app/controllers/web/admin/vacancies_controller.rb
> +    if vacancy_service.call(@vacancy, params[:vacancy]).success?
call - это метод сервиса, который подразумевает совершение какого то бизнеса процесса внутри. По имени не понятно что выполняется. В итоге приходится изучать внутренности метода.

2024-07-25 09:51 UTC, corsicanec82 commented on app/models/vacancy.rb
> +  def cancelation_reason_presence
а почему не стандартный валидатор presence: true с if: -> { условие }
Плюс будут ли валидироваться уже отменные вакансии

2024-07-25 09:51 UTC, corsicanec82 commented on app/models/vacancy.rb
> +    event :cancele do
если не ошибаюсь такого слова нет в англ языке.

2024-07-25 09:51 UTC, corsicanec82 commented on app/models/vacancy.rb
> +      transitions from: %i[on_moderate], to: :canceled
Может ли быть кейс что захотят отменить уже опубликованную вакансию?

2024-07-25 09:51 UTC, corsicanec82 commented on test/fixtures/vacancies.yml
> +  cancelation_reason:  stack_irrelevant
в роли линтера ) - лишний пробел

2024-07-25 09:51 UTC, corsicanec82 commented on app/views/web/admin/vacancies/_cancelation_form.html.slim
> +      = f.input :state_event, as: :state_event, selected: :cancele
нужно ли передавать это из формы?
Эта форма используется только для одной цели - отмены вакансии.
То есть если бы это была универсальная форма по смене стейта для вакансий то понятно зачем select, а в случае одного конкретного действия тут по сути нужны только поле для ввода причины и кнопка отправки формы. Все остальные действия в контроллере (ну или вынесены в сервис)
Кажется что это следствие попытки объединить отмену с обработкой через update
Может сделать для отмены отдельные маршрута get для отрисовки формы и post собственно для обработки. По аналогии как с архиваций например (это я про обработку)
И метод сервис не будет включать смешанную логику

2024-07-25 09:51 UTC, corsicanec82 commented on app/views/web/admin/vacancies/new_cancelation.html.slim
> += render 'cancelation_form', vacancy: @vacancy, url: admin_vacancy_path(@vacancy, go_to: new_cancelation_admin_vacancy_path(@vacancy))
по правде говоря не очень понимаю идею с передачей урла через go_to из формы. Почему мы сразу не можем использовать нужный url для редиректа там где он нужен. Зачем прогонять его через форму?
Поясни пожалуйста

2024-07-25 09:51 UTC, corsicanec82 commented on config/locales/admin/ru.yml
> +          canceled: Отклонить
Просьба сверить имена ключей

2024-07-25 09:51 UTC, corsicanec82 commented on app/views/web/admin/vacancies/new_cancelation.html.slim
> += render 'cancelation_form', vacancy: @vacancy, url: admin_vacancy_path(@vacancy, go_to: new_cancelation_admin_vacancy_path(@vacancy))
думаю что саму форму можно разместить прямо тут. Она ведь нигде не переиспользуется, и просто создаётся лишняя обёртка через render

2024-07-26 20:42 UTC, usernaimandrey commented on app/controllers/web/admin/vacancies_controller.rb
> +    if vacancy_service.call(@vacancy, params[:vacancy]).success?
Так а это что не бизнес-логика): в зависимости от события создается та или иная нотификация, и обычно входной точкой любого сервиса или интерактора является метод call

2024-07-26 20:45 UTC, usernaimandrey commented on app/models/vacancy.rb
> +  def cancelation_reason_presence
Если обновление идет через state_event, то есть через форму, а не через метод  `cancel!` то обычная валидация не срабатывает

2024-07-26 20:49 UTC, usernaimandrey commented on app/views/web/admin/vacancies/new_cancelation.html.slim
> += render 'cancelation_form', vacancy: @vacancy, url: admin_vacancy_path(@vacancy, go_to: new_cancelation_admin_vacancy_path(@vacancy))
Отклонить вакансию можно как с этой страници https://cv.hexlet.io/ru/admin/vacancies/on_moderate так и с этой https://cv.hexlet.io/ru/admin/vacancies что бы знать куда заредиректить после апдейта

2024-07-26 20:51 UTC, usernaimandrey commented on app/models/vacancy.rb
> +      transitions from: %i[on_moderate], to: :canceled
Это надо у овнеров задачи узнать
@fey fyi

2024-07-27 08:34 UTC, corsicanec82 commented on app/controllers/web/admin/vacancies_controller.rb
> +    if vacancy_service.call(@vacancy, params[:vacancy]).success?
> Так а это что не бизнес-логика

В комментарии поинт то другой - проблема именования. Что такой метод усложняет понимание кода. Представь ты видишь где-то в коде вызов User.call(params). И глядя на эту строку ты сможешь ответить, что этот метод делает? Вероятнее всего нет и тебе нужно будет дополнительно изучать логику этого метода, чтобы ответить на этот вопрос.
При наличии в сервисе двух раздельных методов, например VacancyService.update и VacancyService.cancel эта проблема исчезает, так как по имени методов сразу будет понятно какое действие они выполняют.

2024-07-27 08:42 UTC, corsicanec82 commented on app/models/vacancy.rb
> +  def cancelation_reason_presence
А тут всё зависит от условия которое ты пропишешь для стандартного валидатора. Ты же можешь своё логическое выражение указать внутри, как я написано выше if: -> { условие }. И будет такое поведение как тебе нужно. 
```
validates :cancelation_reason, presence: true, if: -> { cancelled? || state_event == 'cancel' }
```
Так ведь сработает?

2024-07-27 08:57 UTC, corsicanec82 commented on app/views/web/admin/vacancies/new_cancelation.html.slim
> += render 'cancelation_form', vacancy: @vacancy, url: admin_vacancy_path(@vacancy, go_to: new_cancelation_admin_vacancy_path(@vacancy))
Хорошо, но здесь же у тебя передаётся всегда один и тот же path независимо от того где был отрисован шаблон, на index или на on_moderate. То есть редиректить всегда будет по одному пути. Вероятно тебе нужно было использовать переменную @go_to которая создаётся в контроллере в соответствующих методах index и on_moderate

2024-07-28 22:04 UTC, usernaimandrey commented on app/controllers/web/admin/vacancies_controller.rb
> +  def vacancy_form
fixed

2024-07-28 22:05 UTC, usernaimandrey commented on app/models/vacancy.rb
> +  def cancelation_reason_presence
Ага поправил

2024-07-28 22:06 UTC, usernaimandrey commented
Все по фиксил

2024-08-02 08:47 UTC, fey commented on app/models/vacancy.rb
> +      transitions from: %i[on_moderate], to: :canceled
Такого не обсуждали, поэтому пока нет, только на модерации. Опубликованную вакансию все равно можно архивнуть.

2024-08-02 10:05 UTC, corsicanec82 requested changes
Почти всё ок. Есть пару небольших неточностей плюс предлагаю несколько упрощений.

2024-08-02 10:05 UTC, corsicanec82 commented on app/mutators/admin/vacancy_mutator.rb
> +      vacancy
кажется тут проще возвращать true, чтобы снаружи отдельно не проверять vacancy.canceled?
метод ведь выполняет одно конкретное действие и результат соответственно однозначный или да или нет

2024-08-09 05:25 UTC, usernaimandrey commented on app/mutators/admin/vacancy_mutator.rb
> +class Admin::VacancyMutator
Решил раз логику разнесли на два метода, то по сути здесь остаётся только работа с базой - обновление вакансии и создание нотификации в БД, обычно же мы такие вещи в мутаторы кладем

2024-08-12 12:13 UTC, fey commented
@usernaimandrey Ну как успехи

2024-08-12 15:02 UTC, usernaimandrey commented
> @usernaimandrey Ну как успехи

Я пока в отпуске, после 18 августа вернусь, внесу правки по предложению Стаса, тут немного осталось)

2024-08-12 16:03 UTC, fey commented
@usernaimandrey хорошего отдыха!

2024-08-12 16:14 UTC, usernaimandrey commented
> @usernaimandrey хорошего отдыха!

Спасибо

2024-08-18 20:46 UTC, usernaimandrey commented on app/mutators/admin/vacancy_mutator.rb
> +class Admin::VacancyMutator
Да и для единобразия другие нотификации создаются тоже в мутаторах, https://github.com/usernaimandrey/hexlet-cv/blob/main/app/mutators/resume/comment_mutator.rb

2024-08-18 20:53 UTC, usernaimandrey commented on app/mutators/admin/vacancy_mutator.rb
> +      vacancy
Тогда можно в этом методе возвращать `vacancy.canceled?` так как если транзакция откатится на этом этапе `vacancy.cancel!` то у нас метод все равно вернет `true`

2024-08-18 21:02 UTC, usernaimandrey commented on .ruby-version
> -ruby-3.2.2
в гем файле поменяли, а тут нет))

2024-08-19 09:56 UTC, corsicanec82 commented on .ruby-version
> +3.3.0
в gemfile стоит условие что версия должна быть больше или равна чем 3.3.0
Тогда уж тут надо ставить версию которая будет использоваться для разработки, и лучше её согласовать  версией в докерфайле
https://github.com/Hexlet/hexlet-cv/blob/caa05075b446966c8122815161d5a7923053ec6b/Dockerfile#L1

2024-08-19 09:56 UTC, corsicanec82 commented on app/mutators/admin/vacancy_mutator.rb
> +      vacancy
Почему ты так считаешь?
Можешь продемонстрировать это например с помощью какого нибудь теста?
Внутри транзакции у тебя используется два метода которые выбрасывают исключение и в этом случае транзакция откатится и выполнение просто не дойдет до строки с true.
Второй момент, что в формах ты же хочешь показать ошибки валидации, а при подходе с raise такой возможности не будет.
Кстати обрати внимание на то как теперь работает обновление вакансии, если например заполнить "невалидно" сущность

2024-08-19 09:58 UTC, corsicanec82 requested changes

2024-08-19 09:58 UTC, corsicanec82 commented on app/controllers/web/admin/vacancies_controller.rb
>        render :edit, status: :unprocessable_entity
в случае ошибки думаю стоит показать флеш сообщение

2024-08-19 09:58 UTC, corsicanec82 commented on app/mutators/admin/vacancy_mutator.rb
> +class Admin::VacancyMutator
Кстати в том примере что ты указываешь посмотри как построена логика (проверка и что возвращается)

2024-08-19 10:08 UTC, grozwalker commented
> Я пока в отпуске, после 18 августа вернусь, внесу правки по предложению Стаса, тут немного  осталось)
ин инглиш, плиз

2024-08-19 10:10 UTC, corsicanec82 commented on app/mutators/admin/vacancy_mutator.rb
> +class Admin::VacancyMutator
Да сделать можно по-разному тут тебе выбирать подход.
Просто суть в том что мутатор преполагает основным действием изменение сущности, попутно например обновляя ещё какие-то. Соответственно возвращается сущность, что логично
Ну и в данном примере просто сделано проще, так как всего есть апдейт сущности и отправка нотификации то не используется выброс исключений, в итоге на выходе в контроллере всё произойдёт как ожидается - будет невалидная сущность и можно будет увидеть ошибки валидации в форме.
Как вариант можешь поступить по аналогии чтобы не писать более сложную логику

2024-08-23 20:10 UTC, usernaimandrey commented on app/mutators/admin/vacancy_mutator.rb
> +      vacancy
![Снимок экрана от 2024-08-23 23-10-30](https://github.com/user-attachments/assets/880aadf6-d374-4f55-bfce-0ead6da7a115)

2024-08-23 20:23 UTC, usernaimandrey commented on app/mutators/admin/vacancy_mutator.rb
> +      vacancy
![Снимок экрана от 2024-08-23 23-10-30](https://github.com/user-attachments/assets/a6ab169b-07c8-449b-8865-a49fc6721922)
Вот этот тест упадет

2024-08-24 14:35 UTC, corsicanec82 commented on app/mutators/admin/vacancy_mutator.rb
> +      vacancy
Так хорошо. А знаешь почему происходит?
Потому что смена стейта по дефолту у aasm не райзит исключение в случае возникновения ошибок валидации модели. То есть простыми словами этот метод в данном случае возвращает просто false. И как следствие транзакция не прерывается, потому тест и падает. 
То есть если ты в тесте добавишь проверку на то был ли отправлен event юзеру то будет видно, что да он отправился, а не должен был. Если бы транзакция была бы прервана то и true не вернулся бы

2024-08-24 14:41 UTC, corsicanec82 commented on app/mutators/admin/vacancy_mutator.rb
> +      vacancy
это добавляешь в тесте
```
notification = Notification.find_by(resource: vacancy, kind: :vacancy_cancel)
assert { !notification }
```
вот такой код проверял (ты за форс пушил но приблизительно было так в мутаторе)
```
ActiveRecord::Base.transaction do
  vacancy.cancel!
  user.notifications.create!(kind: :vacancy_cancel, resource: vacancy)
end

vacancy
```
А вот вывод
<img width="1505" alt="Снимок экрана 2024-08-24 в 17 37 23" src="https://github.com/user-attachments/assets/505f5b07-27da-48fb-b4fb-48798f67129f">

2024-08-24 18:05 UTC, usernaimandrey commented on app/mutators/admin/vacancy_mutator.rb
> +      vacancy
Ага, в текущей реализации такой проблемы быть, не должно, чтобы вакансия не отменилась, а нотификация создалась

2024-08-26 13:57 UTC, fey commented
>ин инглиш, плиз
Mal'chik, review prinesi, my feature hotim.
![image](https://github.com/user-attachments/assets/1cb1d711-d2f1-4202-bb8f-13c57838e44b)

2024-08-28 11:37 UTC, corsicanec82 requested changes
В целом всё ок. Оставил буквально пару небольших комментов, которые по сути не оч критичны

2024-08-28 11:37 UTC, corsicanec82 commented on app/mutators/admin/vacancy_mutator.rb
> +      may_create_notification = params[:state_event] == 'publish' && !vacancy.published?
may_create_notification - это ведь ещё не значит что можно создавать нотификацию, есть же ниже вторая часть условия vacancy.update(params)
лучше уточнить имя. Например, change_to_published

2024-08-28 11:37 UTC, corsicanec82 commented on app/controllers/web/admin/vacancies_controller.rb
> +    if @vacancy.previous_changes.present?
кажется проще проверять @vacancy.invalid?

2024-08-28 11:37 UTC, corsicanec82 commented on app/controllers/web/admin/vacancies_controller.rb
> +    @vacancy = Admin::VacancyMutator.update(vacancy, params.permit![:vacancy])
а permit! здесь нужен? Мы же используем форму в которой прописаны все разрешенные поля

2024-08-28 11:37 UTC, corsicanec82 commented on app/controllers/web/admin/vacancies_controller.rb
> +      redirect_to params[:go_to] || new_cancelation_admin_vacancy_path(@vacancy)
после успешной отмены вакансии мы остаёмся на этой же странице. И как думаешь что произойдёт если снова нажать на кнопку изменить?
Думаю стоит добавить гард экспрешн в метод cancel! в мутаторе

2024-08-29 12:37 UTC, corsicanec82 requested changes

2024-08-29 12:37 UTC, corsicanec82 commented on app/mutators/admin/vacancy_mutator.rb
> +      vacancy.save and return vacancy if vacancy.canceled?
vacancy.save выглядит так как будто мы разрешаем апдейтить cancelation_reason, а это тоже самое что разрешить в стейт машине переход из cancelled в т.ч
Соответственно если нужно такое поведение то там и стоит разрешить переход. И просто поправыить условие для отправки нотификации.
Если же такое поведение не требуется (а скорее всего так и должно быть), то тогда и апдейтить значит не нужно.
В ином случае полчится странная штука. Что вначале отменили вакансию, пользователю ушла нотификация а потом причину отредачили без уведомления. В итоге пользователь будет очень удивлен почему причина на сайте отличается от той, о которой ему сообщили.

2024-08-29 18:56 UTC, usernaimandrey commented on app/mutators/admin/vacancy_mutator.rb
> +      vacancy.save and return vacancy if vacancy.canceled?
да ты прав, fixed

2024-08-30 06:14 UTC, corsicanec82 approved these changes

2024-08-30 06:15 UTC, merged